Repository pingcap/tispark, pull requests merged in 2019-10, with the labels that each got.

#1139 Forbid to add TiDB password to SparkConf
  core/src/main/scala/com/pingcap/tispark/TiDBOptions.scala
  docs/datasource_api_userguide.md
Labels: needs-cherry-pick-2.2

#1148 Fix Bit Type default value bug
  core/src/test/scala/org/apache/spark/sql/IssueTestSuite.scala
  core/src/test/scala/org/apache/spark/sql/QueryTest.scala
  tikv-client/src/main/java/com/pingcap/tikv/meta/TiColumnInfo.java
  tikv-client/src/main/java/com/pingcap/tikv/meta/TiTableInfo.java
  tikv-client/src/main/java/com/pingcap/tikv/types/BitType.java
Labels: needs-cherry-pick-2.1, needs-cherry-pick-2.2

#1152 [cherry-pick] Fix Bit Type default value bug (#1148)
  core/src/test/scala/org/apache/spark/sql/IssueTestSuite.scala
  core/src/test/scala/org/apache/spark/sql/QueryTest.scala
  tikv-client/src/main/java/com/pingcap/tikv/meta/TiColumnInfo.java
  tikv-client/src/main/java/com/pingcap/tikv/meta/TiTableInfo.java
  tikv-client/src/main/java/com/pingcap/tikv/types/BitType.java
Labels: CHERRY-PICK

#1153 [cherry-pick] Fix Bit Type default value bug (#1148)
  core/src/test/scala/org/apache/spark/sql/IssueTestSuite.scala
  core/src/test/scala/org/apache/spark/sql/QueryTest.scala
  tikv-client/src/main/java/com/pingcap/tikv/meta/TiColumnInfo.java
  tikv-client/src/main/java/com/pingcap/tikv/meta/TiTableInfo.java
  tikv-client/src/main/java/com/pingcap/tikv/types/BitType.java
Labels: CHERRY-PICK

#1150 revert: fix cost model
  tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java
Labels: needs-cherry-pick-2.1, needs-cherry-pick-2.2

#1164 change jenkins home
  .ci/build.groovy
  .ci/integration_test.groovy
Labels: needs-cherry-pick-2.1, needs-cherry-pick-2.2

#1162 Fix No Matching column bug
  core/src/main/scala/com/pingcap/tispark/TiConfigConst.scala
  core/src/main/scala/org/apache/spark/sql/TiStrategy.scala
  core/src/test/scala/org/apache/spark/sql/IssueTestSuite.scala
Labels: needs-cherry-pick-2.2, needs-cherry-pick-master

#1167 [cherry-pick] Fix No Matching column bug (#1162)
  core/src/main/scala/com/pingcap/tispark/TiConfigConst.scala
  core/src/main/scala/org/apache/spark/sql/TiStrategy.scala
  core/src/test/scala/org/apache/spark/sql/IssueTestSuite.scala
Labels: CHERRY-PICK
