Repository pingcap/tispark, pull requests merged in 2019-09, with the labels that each got.

#1088 [cherry-pick] fix range partition throw UnsupportedSyntaxException error
  core/src/test/scala/org/apache/spark/sql/PartitionTableSuite.scala
  tikv-client/src/main/java/com/pingcap/tikv/expression/visitor/PrunedPartitionBuilder.java
Labels: CHERRY-PICK

#1095 rename tispark core maven name
  assembly/pom.xml
  assembly/src/main/assembly/assembly.xml
  core-test/pom.xml
  core/pom.xml
  spark-wrapper/spark-2.3/pom.xml
  spark-wrapper/spark-2.4/pom.xml
Labels: needs-cherry-pick-2.2

#1098 [cherry-pick] rename tispark core maven name
  assembly/pom.xml
  assembly/src/main/assembly/assembly.xml
  core-test/pom.xml
  core/pom.xml
  spark-wrapper/spark-2.3/pom.xml
  spark-wrapper/spark-2.4/pom.xml
Labels: CHERRY-PICK

#1101 add field type on each expr
  tikv-client/src/main/java/com/pingcap/tikv/expression/visitor/ProtoConverter.java
Labels: needs-cherry-pick-2.2

#1104 Support reading data from TiDB in Spark Structured Streaming
  core/src/main/scala/org/apache/spark/sql/TiStrategy.scala
Labels: CHANGELOG, needs-cherry-pick-2.1, needs-cherry-pick-2.2

#1108 Fix bug: TiSpark Catalog has 10-20s delay
  README.md
  core/src/main/scala/com/pingcap/tispark/MetaManager.scala
  core/src/main/scala/com/pingcap/tispark/TiConfigConst.scala
  core/src/main/scala/com/pingcap/tispark/utils/TiUtil.scala
  core/src/test/scala/org/apache/spark/sql/BaseTiSparkTest.scala
  core/src/test/scala/org/apache/spark/sql/IssueTestSuite.scala
  tikv-client/src/main/java/com/pingcap/tikv/TiConfiguration.java
  tikv-client/src/main/java/com/pingcap/tikv/TiSession.java
  tikv-client/src/main/java/com/pingcap/tikv/catalog/Catalog.java
Labels: CHANGELOG, needs-cherry-pick-2.1, needs-cherry-pick-2.2

#1111 [cherry-pick] Fix bug: TiSpark Catalog has 10-20s delay (#1108)
  README.md
  core/src/main/scala/com/pingcap/tispark/MetaManager.scala
  core/src/main/scala/com/pingcap/tispark/TiConfigConst.scala
  core/src/main/scala/com/pingcap/tispark/utils/TiUtil.scala
  core/src/test/scala/org/apache/spark/sql/IssueTestSuite.scala
  tikv-client/src/main/java/com/pingcap/tikv/TiConfiguration.java
  tikv-client/src/main/java/com/pingcap/tikv/TiSession.java
  tikv-client/src/main/java/com/pingcap/tikv/catalog/Catalog.java
Labels: CHERRY-PICK

#1115 Update spark to 2.3.4 and 2.4.4
  docs/userguide.md
  pom.xml
  spark-wrapper/spark-2.3/pom.xml
  spark-wrapper/spark-2.4/pom.xml
Labels: CHANGELOG, needs-cherry-pick-2.1, needs-cherry-pick-2.2

#1116 Remove recreate flag when creating TiSession
  core/src/main/scala/org/apache/spark/sql/TiContext.scala
  tikv-client/src/main/java/com/pingcap/tikv/TiSession.java
Labels: needs-cherry-pick-2.1, needs-cherry-pick-2.2

#1122 [cherry-pick] Print exception when ut fails (#1113)
  core/src/test/scala/org/apache/spark/sql/QueryTest.scala
Labels: CHERRY-PICK

#1119 [cherry-pick] Update spark to 2.3.4 and 2.4.4 (#1115)
  docs/userguide.md
  pom.xml
  spark-wrapper/spark-2.3/pom.xml
  spark-wrapper/spark-2.4/pom.xml
Labels: CHERRY-PICK

#1120 [cherry-pick] Update spark to 2.3.4 and 2.4.4 (#1115)
  docs/userguide.md
  pom.xml
  python/setup.py
Labels: CHERRY-PICK

#1126 Fix ci: IssueTestSuite failed if run DataSourceWithoutExtensionsSuite before IssueTestSuite
  .ci/integration_test.groovy
  core/src/test/scala/org/apache/spark/sql/test/SharedSQLContext.scala
Labels: needs-cherry-pick-2.2

#1118 [cherry-pick] Remove recreate flag when creating tisession (#1116)
  core/src/main/scala/org/apache/spark/sql/TiContext.scala
  tikv-client/src/main/java/com/pingcap/tikv/TiSession.java
Labels: CHERRY-PICK

#1128 [cherry-pick] Fix ci: IssueTestSuite failed if run DataSourceWithoutExtensionsSuite…
  .ci/integration_test.groovy
  core/src/test/scala/org/apache/spark/sql/test/SharedSQLContext.scala
Labels: CHERRY-PICK

#1127 fix fastxml security alert
  tikv-client/pom.xml
Labels: needs-cherry-pick-2.1, needs-cherry-pick-2.2

#1130 [cherry-pick] Fix fastxml security alert (#1127)
  tikv-client/pom.xml
Labels: CHERRY-PICK

#1129 [cherry-pick] Fix fastxml security alert (#1127)
  tikv-client/pom.xml
Labels: CHERRY-PICK

#1133 fix ci
  core/src/test/scala/com/pingcap/tispark/overflow/BitOverflowSuite.scala
Labels: needs-cherry-pick-2.2

#1135 [cherry-pick] Fix ci: tidb error message changed to "Data truncation: Data too lon…
  core/src/test/scala/com/pingcap/tispark/overflow/BitOverflowSuite.scala
Labels: CHERRY-PICK
