Repository pingcap/tispark, pull requests merged in 2019-11, with the labels that each got.

#1185 Fix topn
  core/src/main/scala/com/pingcap/tispark/TiConfigConst.scala
  core/src/main/scala/org/apache/spark/sql/TiStrategy.scala
Labels: needs-cherry-pick-2.1, needs-cherry-pick-2.2

#1179 Fix Stack Overflow Error when reading from partition table
  core/src/main/scala/org/apache/spark/sql/execution/CoprocessorRDD.scala
  core/src/test/scala/org/apache/spark/sql/PartitionTableSuite.scala
Labels: needs-cherry-pick-2.2, needs-cherry-pick-master

#1189 [cherry-pick] Fix Stack Overflow Error when reading from partition table (#1179)
  core/src/main/scala/org/apache/spark/sql/execution/CoprocessorRDD.scala
  core/src/test/scala/org/apache/spark/sql/PartitionTableSuite.scala
Labels: CHERRY-PICK

#1188 [cherry-pick] Fix Stack Overflow Error when reading from partition table (#1179)
  core/src/main/scala/org/apache/spark/sql/execution/CoprocessorRDD.scala
  core/src/test/scala/org/apache/spark/sql/PartitionTableSuite.scala
Labels: CHERRY-PICK

#1187 Consider nulls order in TopN push down
  core/src/main/scala/org/apache/spark/sql/TiStrategy.scala
  core/src/test/scala/org/apache/spark/sql/BaseTiSparkTest.scala
  core/src/test/scala/org/apache/spark/sql/IssueTestSuite.scala
Labels: needs-cherry-pick-2.1, needs-cherry-pick-2.2

#1190 Fix TopN push down (#1185)
  core/src/main/scala/com/pingcap/tispark/TiConfigConst.scala
  core/src/main/scala/org/apache/spark/sql/TiStrategy.scala
Labels: CHERRY-PICK

#1191 Fix TopN push down (#1185)
  core/src/main/scala/com/pingcap/tispark/TiConfigConst.scala
  core/src/main/scala/org/apache/spark/sql/TiStrategy.scala
Labels: CHERRY-PICK

#1194 Consider nulls order in TopN pushdown (#1187)
  core/src/main/scala/org/apache/spark/sql/TiStrategy.scala
  core/src/test/scala/org/apache/spark/sql/BaseTiSparkTest.scala
  core/src/test/scala/org/apache/spark/sql/IssueTestSuite.scala
Labels: CHERRY-PICK

#1193 Consider nulls order in TopN pushdown (#1187)
  core/src/main/scala/org/apache/spark/sql/TiStrategy.scala
  core/src/test/scala/org/apache/spark/sql/BaseTiSparkSuite.scala
  core/src/test/scala/org/apache/spark/sql/IssueTestSuite.scala
  core/src/test/scala/org/apache/spark/sql/QueryTest.scala
  core/src/test/scala/org/apache/spark/sql/benchmark/TPCDSQuerySuite.scala
  core/src/test/scala/org/apache/spark/sql/benchmark/TPCHQuerySuite.scala
  core/src/test/scala/org/apache/spark/sql/txn/TxnTestSuite.scala
Labels: CHERRY-PICK

#1207 Fix task retry if tikv is down
  tikv-client/src/main/java/com/pingcap/tikv/operation/KVErrorHandler.java
  tikv-client/src/main/java/com/pingcap/tikv/policy/RetryPolicy.java
  tikv-client/src/main/java/com/pingcap/tikv/region/RegionStoreClient.java
Labels: needs-cherry-pick-2.2, needs-cherry-pick-master

#1212 [cherry-pick] Fix task retry if tikv is down (#1207)
  tikv-client/src/main/java/com/pingcap/tikv/operation/KVErrorHandler.java
  tikv-client/src/main/java/com/pingcap/tikv/policy/RetryPolicy.java
  tikv-client/src/main/java/com/pingcap/tikv/region/RegionStoreClient.java
Labels: CHERRY-PICK

#1192 Add columnar execution for TiSpark
  core/src/main/scala/com/pingcap/tispark/TiConfigConst.scala
  core/src/main/scala/com/pingcap/tispark/TiDBRelation.scala
  core/src/main/scala/com/pingcap/tispark/statistics/StatisticsManager.scala
  core/src/main/scala/com/pingcap/tispark/utils/ReflectionUtil.scala
  core/src/main/scala/com/pingcap/tispark/utils/TiUtil.scala
  core/src/main/scala/org/apache/spark/sql/TiStrategy.scala
  core/src/main/scala/org/apache/spark/sql/execution/CoprocessorRDD.scala
  core/src/main/scala/org/apache/spark/sql/execution/TiColumnarBatchScan.scala
  core/src/main/scala/org/apache/spark/sql/execution/TiConverter.scala
  core/src/main/scala/org/apache/spark/sql/tispark/TiHandleRDD.scala
  core/src/main/scala/org/apache/spark/sql/tispark/TiRDD.scala
  core/src/main/scala/org/apache/spark/sql/tispark/TiRowRDD.scala
  core/src/test/scala/org/apache/spark/sql/IssueTestSuite.scala
  core/src/test/scala/org/apache/spark/sql/PartitionTableSuite.scala
  core/src/test/scala/org/apache/spark/sql/benchmark/TPCHQuerySuite.scala
  core/src/test/scala/org/apache/spark/sql/catalyst/plans/BasePlanTest.scala
  core/src/test/scala/org/apache/spark/sql/statistics/StatisticsManagerSuite.scala
  core/src/test/scala/org/apache/spark/sql/test/generator/Schema.scala
  spark-wrapper/spark-2.3/src/main/scala/org/apache/spark/sql/TiAggregationImpl.scala
  spark-wrapper/spark-2.4/src/main/scala/org/apache/spark/sql/TiAggregationImpl.scala
  tikv-client/README.md
  tikv-client/pom.xml
  tikv-client/src/main/java/com/pingcap/tikv/Snapshot.java
  tikv-client/src/main/java/com/pingcap/tikv/TiConfiguration.java
  tikv-client/src/main/java/com/pingcap/tikv/columnar/RowwiseTiColumnarVector.java
  tikv-client/src/main/java/com/pingcap/tikv/columnar/TiChunkColumn.java
  tikv-client/src/main/java/com/pingcap/tikv/columnar/TiColumnVector.java
  tikv-client/src/main/java/com/pingcap/tikv/columnar/TiColumnarArray.java
  tikv-client/src/main/java/com/pingcap/tikv/columnar/TiColumnarBatch.java
  tikv-client/src/main/java/com/pingcap/tikv/columnar/TiColumnarMap.java
  tikv-client/src/main/java/com/pingcap/tikv/columnar/TiColumnarRow.java
  tikv-client/src/main/java/com/pingcap/tikv/operation/iterator/CoprocessIterator.java
  tikv-client/src/main/java/com/pingcap/tikv/row/DefaultChunkReader.java
  tikv-client/src/main/java/com/pingcap/tikv/types/AbstractDateTimeType.java
  tikv-client/src/main/java/com/pingcap/tikv/types/DataType.java
  tikv-client/src/main/java/com/pingcap/tikv/types/DateTimeType.java
  tikv-client/src/main/java/com/pingcap/tikv/types/DateType.java
  tikv-client/src/main/java/com/pingcap/tikv/types/DecimalType.java
  tikv-client/src/main/java/com/pingcap/tikv/types/MySQLType.java
  tikv-client/src/main/java/com/pingcap/tikv/types/TimestampType.java
  tikv-client/src/main/java/com/pingcap/tikv/util/MemoryUtil.java
  tikv-client/src/main/java/com/pingcap/tikv/util/TypeMapping.java
Labels: enhancement

#1210 set raft store capacity
  config/tikv.toml
Labels: needs-cherry-pick-2.1, needs-cherry-pick-2.2

#1229 use `df.limit(1).count` instead of `df.count` to express `df.isEmpty`
  core/src/main/scala/com/pingcap/tispark/TiBatchWrite.scala
  core/src/main/scala/com/pingcap/tispark/utils/TiUtil.scala
Labels: needs-cherry-pick-2.2

#1239 [cherry-pick] use `df.limit(1).count` instead of `df.count` to express `df.isEmpty`
  core/src/main/scala/com/pingcap/tispark/TiBatchWrite.scala
  core/src/main/scala/com/pingcap/tispark/utils/TiUtil.scala
Labels: CHERRY-PICK

#1242 disable set, enum and bit pushed down
  core/src/main/scala/com/pingcap/tispark/utils/TiUtil.scala
  core/src/main/scala/org/apache/spark/sql/TiStrategy.scala
  tikv-client/src/main/java/com/pingcap/tikv/types/BitType.java
  tikv-client/src/main/java/com/pingcap/tikv/types/DataType.java
  tikv-client/src/main/java/com/pingcap/tikv/types/EnumType.java
  tikv-client/src/main/java/com/pingcap/tikv/types/JsonType.java
  tikv-client/src/main/java/com/pingcap/tikv/types/SetType.java
  tikv-client/src/main/java/com/pingcap/tikv/types/UninitializedType.java
Labels: needs-cherry-pick-2.1, needs-cherry-pick-2.2

#1249 cache data before write
  core/src/main/scala/com/pingcap/tispark/TiBatchWrite.scala
Labels: needs-cherry-pick-2.2

#1250 [cherry-pick] cache data before write (#1249)
  core/src/main/scala/com/pingcap/tispark/TiBatchWrite.scala
Labels: CHERRY-PICK

#1252 fix datetime year overflow error message
  core/src/test/scala/com/pingcap/tispark/datasource/BaseDataSourceTest.scala
  core/src/test/scala/com/pingcap/tispark/overflow/BitOverflowSuite.scala
  core/src/test/scala/com/pingcap/tispark/overflow/BytesOverflowSuite.scala
  core/src/test/scala/com/pingcap/tispark/overflow/DateOverflowSuite.scala
  core/src/test/scala/com/pingcap/tispark/overflow/DateTimeOverflowSuite.scala
  core/src/test/scala/com/pingcap/tispark/overflow/DecimalOverflowSuite.scala
  core/src/test/scala/com/pingcap/tispark/overflow/EnumOverflowSuite.scala
  core/src/test/scala/com/pingcap/tispark/overflow/SignedOverflowSuite.scala
  core/src/test/scala/com/pingcap/tispark/overflow/StringOverflowSuite.scala
  core/src/test/scala/com/pingcap/tispark/overflow/UnsignedOverflowSuite.scala
Labels: needs-cherry-pick-2.2

#1257 [cherry-pick] fix datetime year overflow (#1252)
  core/src/test/scala/com/pingcap/tispark/datasource/BaseDataSourceTest.scala
  core/src/test/scala/com/pingcap/tispark/overflow/BitOverflowSuite.scala
  core/src/test/scala/com/pingcap/tispark/overflow/BytesOverflowSuite.scala
  core/src/test/scala/com/pingcap/tispark/overflow/DateOverflowSuite.scala
  core/src/test/scala/com/pingcap/tispark/overflow/DateTimeOverflowSuite.scala
  core/src/test/scala/com/pingcap/tispark/overflow/DecimalOverflowSuite.scala
  core/src/test/scala/com/pingcap/tispark/overflow/EnumOverflowSuite.scala
  core/src/test/scala/com/pingcap/tispark/overflow/SignedOverflowSuite.scala
  core/src/test/scala/com/pingcap/tispark/overflow/StringOverflowSuite.scala
  core/src/test/scala/com/pingcap/tispark/overflow/UnsignedOverflowSuite.scala
Labels: CHERRY-PICK

#1267 Register udf for every sparksession (#1258)
  core/src/main/scala/com/pingcap/tispark/TiSparkInfo.scala
  core/src/main/scala/com/pingcap/tispark/utils/TiUtil.scala
  core/src/main/scala/org/apache/spark/sql/TiContext.scala
  core/src/main/scala/org/apache/spark/sql/TiExtensions.scala
Labels: CHERRY-PICK
