Repository pingcap/tispark, pull requests merged in 2019-08, with the labels that each got.

#972 fix java.lang.IncompatibleClassChangeError when submit with spark-2.4.3
  core/src/main/scala/com/pingcap/tispark/utils/ReflectionUtil.scala
  core/src/main/scala/org/apache/spark/sql/TiContext.scala
  core/src/main/scala/org/apache/spark/sql/TiStrategy.scala
  core/src/main/scala/org/apache/spark/sql/catalyst/catalog/TiConcreteSessionCatalog.scala
  core/src/main/scala/org/apache/spark/sql/catalyst/expressions/aggregate/SpecialSum.scala
  core/src/main/scala/org/apache/spark/sql/execution/CoprocessorRDD.scala
  core/src/main/scala/org/apache/spark/sql/execution/command/tables.scala
  core/src/main/scala/org/apache/spark/sql/extensions/rules.scala
  spark-wrapper/spark-2.3/src/main/scala/com/pingcap/tispark/SparkWrapper.scala
  spark-wrapper/spark-2.4/src/main/scala/com/pingcap/tispark/SparkWrapper.scala
Labels: needs-cherry-pick-2.2

#963 improve TiConfiguration getPdAddrsString function
  core/src/main/scala/com/pingcap/tispark/TiBatchWrite.scala
  core/src/main/scala/org/apache/spark/sql/execution/CoprocessorRDD.scala
  core/src/main/scala/org/apache/spark/sql/tispark/TiHandleRDD.scala
  core/src/main/scala/org/apache/spark/sql/tispark/TiRDD.scala
  tikv-client/src/main/java/com/pingcap/tikv/Snapshot.java
  tikv-client/src/main/java/com/pingcap/tikv/TiConfiguration.java
  tikv-client/src/main/java/com/pingcap/tikv/TiSession.java
  tikv-client/src/main/java/com/pingcap/tikv/TiSessionCache.java
  tikv-client/src/main/java/com/pingcap/tikv/TwoPhaseCommitter.java
  tikv-client/src/main/java/com/pingcap/tikv/allocator/RowIDAllocator.java
  tikv-client/src/test/java/com/pingcap/tikv/TiConfigurationTest.java
Labels: needs-cherry-pick-2.2

#991 add spark sql document for batch write
  docs/datasource_api_userguide.md
Labels: needs-cherry-pick-2.2

#995 fix index scan bug
  tikv-client/src/main/java/com/pingcap/tikv/meta/TiDAGRequest.java
  tikv-client/src/main/java/com/pingcap/tikv/operation/iterator/CoprocessIterator.java
  tikv-client/src/test/java/com/pingcap/tikv/operation/iterator/DAGIteratorTest.java
Labels: CHANGELOG, needs-cherry-pick-2.1, needs-cherry-pick-2.2

#1010 Fix scala compiler version
  core/pom.xml
  pom.xml
  spark-wrapper/spark-2.3/pom.xml
  spark-wrapper/spark-2.4/pom.xml
Labels: needs-cherry-pick-2.2

#1018 [cherry-pick] fix reflection bug for hdp release (#1017)
  core/src/main/scala/com/pingcap/tispark/utils/ReflectionUtil.scala
Labels: CHERRY-PICK

#1019 Cherry-pick Fix scala compiler version (#1010)
  core/pom.xml
  pom.xml
Labels: CHERRY-PICK

#1020 Cherry-pick Fix scala compiler version (#1010)
  core/pom.xml
  pom.xml
  spark-wrapper/spark-2.3/pom.xml
  spark-wrapper/spark-2.4/pom.xml
Labels: CHERRY-PICK

#1024 [cherry-pick] fix index scan bug
  tikv-client/src/main/java/com/pingcap/tikv/meta/TiDAGRequest.java
  tikv-client/src/main/java/com/pingcap/tikv/operation/iterator/CoprocessIterator.java
  tikv-client/src/test/java/com/pingcap/tikv/operation/iterator/DAGIteratorTest.java
Labels: CHERRY-PICK

#1023 [cherry-pick] fix cost model in table scan
  tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java
Labels: CHERRY-PICK

#1027 [cherry-pick] prohibit agg or groupby pushdown on double read (#1004)
  tikv-client/src/main/java/com/pingcap/tikv/meta/TiDAGRequest.java
Labels: CHERRY-PICK

#1035 [cherry-pick] 2.1.3 release notes (#1026)
  CHANGELOG.md
Labels: CHERRY-PICK

#1031 set tikv region size from 96M to 1M
  .ci/integration_test.groovy
  config/tikv.toml
  core/src/test/scala/org/apache/spark/sql/test/SharedSQLContext.scala
Labels: needs-cherry-pick-2.1

#1052 [cherry-pick] fix reflection bug: pass in different arguments for different version…
  core/src/main/scala/com/pingcap/tispark/utils/ReflectionUtil.scala
Labels: CHERRY-PICK

#1054 fix distinct without alias bug: disable pushdown aggregate with alias
  core/src/main/scala/org/apache/spark/sql/TiStrategy.scala
  core/src/test/scala/org/apache/spark/sql/BaseTiSparkTest.scala
  core/src/test/scala/org/apache/spark/sql/IssueTestSuite.scala
Labels: CHERRY-PICK

#1069 [cherry-pick] release tispark-2.1.4 (#1068)
  CHANGELOG.md
Labels: CHERRY-PICK

#1075 Remove useless dependencies
  core/pom.xml
  spark-wrapper/spark-2.3/pom.xml
  spark-wrapper/spark-2.4/pom.xml
  tikv-client/pom.xml
Labels: needs-cherry-pick-2.1, needs-cherry-pick-2.2
