Repository pingcap/tispark, pull requests merged in 2019-12, with the labels that each got.

#1274 [cherry-pick] Register udf for every sparksession (#1258)
  core/src/main/scala/com/pingcap/tispark/utils/TiUtil.scala
  core/src/main/scala/org/apache/spark/sql/TiContext.scala
  core/src/main/scala/org/apache/spark/sql/TiExtensions.scala
Labels: CHERRY-PICK

#1275 Add timezone check
  core/src/main/scala/com/pingcap/tispark/utils/TiUtil.scala
  core/src/main/scala/org/apache/spark/sql/tispark/TiHandleRDD.scala
  core/src/main/scala/org/apache/spark/sql/tispark/TiRDD.scala
  tikv-client/src/main/java/com/pingcap/tikv/TiConfiguration.java
  tikv-client/src/main/java/com/pingcap/tikv/exception/TiInternalException.java
Labels: needs-cherry-pick-2.2, needs-cherry-pick-master

#1281 [cherry-pick] Add timezone check #1275
  core/src/main/scala/com/pingcap/tispark/utils/TiUtil.scala
  core/src/main/scala/org/apache/spark/sql/tispark/TiHandleRDD.scala
  core/src/main/scala/org/apache/spark/sql/tispark/TiRowRDD.scala
  tikv-client/src/main/java/com/pingcap/tikv/TiConfiguration.java
  tikv-client/src/main/java/com/pingcap/tikv/exception/TiInternalException.java
  tikv-client/src/main/java/com/pingcap/tikv/types/Converter.java
Labels: CHERRY-PICK

#1280 [cherry-pick] Add timezone check (#1275)
  core/src/main/scala/com/pingcap/tispark/utils/TiUtil.scala
  core/src/main/scala/org/apache/spark/sql/tispark/TiHandleRDD.scala
  core/src/main/scala/org/apache/spark/sql/tispark/TiRowRDD.scala
  tikv-client/src/main/java/com/pingcap/tikv/TiConfiguration.java
  tikv-client/src/main/java/com/pingcap/tikv/exception/TiInternalException.java
  tikv-client/src/main/java/com/pingcap/tikv/types/Converter.java
Labels: CHERRY-PICK

#1277 Remove conflicting dbPrefix setting in TiDBOptions
  core/src/main/scala/com/pingcap/tispark/TiBatchWrite.scala
  core/src/main/scala/com/pingcap/tispark/TiDBDataSource.scala
  core/src/main/scala/com/pingcap/tispark/TiDBOptions.scala
Labels: needs-cherry-pick-2.2

#1284 Remove conflicting dbPrefix setting in TiDBOptions (#1277)
  core/src/main/scala/com/pingcap/tispark/TiBatchWrite.scala
  core/src/main/scala/com/pingcap/tispark/TiDBDataSource.scala
  core/src/main/scala/com/pingcap/tispark/TiDBOptions.scala
Labels: CHERRY-PICK

#1286 [cherry-pick] disable set and enum push down for release 2.1
  core/src/main/scala/com/pingcap/tispark/utils/TiUtil.scala
  core/src/main/scala/org/apache/spark/sql/TiStrategy.scala
  tikv-client/src/main/java/com/pingcap/tikv/types/BitType.java
  tikv-client/src/main/java/com/pingcap/tikv/types/DataType.java
  tikv-client/src/main/java/com/pingcap/tikv/types/EnumType.java
  tikv-client/src/main/java/com/pingcap/tikv/types/JsonType.java
  tikv-client/src/main/java/com/pingcap/tikv/types/SetType.java
Labels: CHERRY-PICK

#1287 [cherry-pick] disable set and enum push down for release 2.2
  core/src/main/scala/com/pingcap/tispark/utils/TiUtil.scala
  core/src/main/scala/org/apache/spark/sql/TiStrategy.scala
  tikv-client/src/main/java/com/pingcap/tikv/types/BitType.java
  tikv-client/src/main/java/com/pingcap/tikv/types/DataType.java
  tikv-client/src/main/java/com/pingcap/tikv/types/EnumType.java
  tikv-client/src/main/java/com/pingcap/tikv/types/JsonType.java
  tikv-client/src/main/java/com/pingcap/tikv/types/SetType.java
  tikv-client/src/main/java/com/pingcap/tikv/types/UninitializedType.java
Labels: CHERRY-PICK

#1259 Add multi-session test
  core/src/main/scala/com/pingcap/tispark/TiDBRelation.scala
  core/src/test/scala/com/pingcap/tispark/datasource/DataSourceWithoutExtensionsSuite.scala
  core/src/test/scala/org/apache/spark/SharedSparkContext.scala
  core/src/test/scala/org/apache/spark/SparkFunSuite.scala
  core/src/test/scala/org/apache/spark/sql/BaseTestGenerationSpec.scala
  core/src/test/scala/org/apache/spark/sql/BaseTiSparkTest.scala
  core/src/test/scala/org/apache/spark/sql/MultipleSparkSessionTestSuite.scala
  core/src/test/scala/org/apache/spark/sql/test/SharedSQLContext.scala
  core/src/test/scala/org/apache/spark/sql/test/TestSparkSession.scala
  core/src/test/scala/org/apache/spark/sql/txn/TxnTestSuite.scala
  core/src/test/scala/org/apache/spark/sql/types/BaseDataTypeTest.scala
  core/src/test/scala/org/apache/spark/sql/types/DataTypeExampleTest.scala
  core/src/test/scala/org/apache/spark/sql/types/DataTypeNormalSuite.scala
  core/src/test/scala/org/apache/spark/sql/types/MultiColumnDataTypeTest.scala
  core/src/test/scala/org/apache/spark/sql/types/pk/DataTypePKSuite.scala
Labels: needs-cherry-pick-2.1, needs-cherry-pick-2.2

#1288 Fix unique key restriction in test
  core/src/test/scala/org/apache/spark/sql/test/generator/ColumnValueGenerator.scala
  core/src/test/scala/org/apache/spark/sql/test/generator/TestDataGenerator.scala
Labels: needs-cherry-pick-2.2

#1291 Add multi-session test (#1259)
  core/src/main/scala/com/pingcap/tispark/TiDBRelation.scala
  core/src/test/scala/com/pingcap/tispark/datasource/DataSourceWithoutExtensionsSuite.scala
  core/src/test/scala/org/apache/spark/SharedSparkContext.scala
  core/src/test/scala/org/apache/spark/SparkFunSuite.scala
  core/src/test/scala/org/apache/spark/sql/BaseTestGenerationSpec.scala
  core/src/test/scala/org/apache/spark/sql/BaseTiSparkTest.scala
  core/src/test/scala/org/apache/spark/sql/MultipleSparkSessionTestSuite.scala
  core/src/test/scala/org/apache/spark/sql/test/SharedSQLContext.scala
  core/src/test/scala/org/apache/spark/sql/test/TestSparkSession.scala
  core/src/test/scala/org/apache/spark/sql/txn/TxnTestSuite.scala
  core/src/test/scala/org/apache/spark/sql/types/BaseDataTypeTest.scala
  core/src/test/scala/org/apache/spark/sql/types/DataTypeExampleTest.scala
  core/src/test/scala/org/apache/spark/sql/types/DataTypeNormalSuite.scala
  core/src/test/scala/org/apache/spark/sql/types/MultiColumnDataTypeTest.scala
  core/src/test/scala/org/apache/spark/sql/types/pk/DataTypePKSuite.scala
Labels: CHERRY-PICK

#1300 Add ci argument for region size
  .ci/integration_test.groovy
  config/tikv.toml
Labels: needs-cherry-pick-2.2

#1305 add release notes for 2.1.8
  CHANGELOG.md
Labels: needs-cherry-pick-master

#1310 add developer
  pom.xml
Labels: needs-cherry-pick-2.1, needs-cherry-pick-2.2

#1309 Add A Link to TiSpark Examples
  README.md
Labels: needs-cherry-pick-2.2

#1308 fix Residual Filter containing wrong info
  core/src/main/scala/com/pingcap/tispark/utils/TiUtil.scala
  core/src/main/scala/org/apache/spark/sql/tispark/TiHandleRDD.scala
  core/src/test/scala/org/apache/spark/sql/PartitionTableSuite.scala
  core/src/test/scala/org/apache/spark/sql/catalyst/plans/logical/LogicalPlanTestSuite.scala
  tikv-client/src/main/java/com/pingcap/tikv/meta/TiDAGRequest.java
Labels: needs-cherry-pick-2.1, needs-cherry-pick-2.2

#1315 [cherry-pick] update ci script for release-2.1
  .ci/integration_test.groovy
  .ci/log4j-ci.properties
  core/pom.xml
  core/scripts/fetch-test-data.sh
  core/scripts/version.sh
  pom.xml
  tikv-client/pom.xml
  tikv-client/scripts/proto.sh
Labels: CHERRY-PICK

#1323 Fix desc temp view
  core/src/main/scala/org/apache/spark/sql/execution/command/tables.scala
  core/src/test/scala/org/apache/spark/sql/catalyst/catalog/CatalogTestSuite.scala
Labels: needs-cherry-pick-2.1, needs-cherry-pick-2.2

#1328 fix desc temp view (#1323)
  core/src/main/scala/org/apache/spark/sql/execution/command/tables.scala
  core/src/test/scala/org/apache/spark/sql/catalyst/catalog/CatalogTestSuite.scala
Labels: CHERRY-PICK

#1333 Fix prefix index on blob
  tikv-client/src/main/java/com/pingcap/tikv/types/Converter.java
  tikv-client/src/test/java/com/pingcap/tikv/types/ConverterTest.java
Labels: needs-cherry-pick-2.1, needs-cherry-pick-2.2

#1340 modify ci default mode to full-mode
  .ci/integration_test.groovy
Labels: needs-cherry-pick-2.1, needs-cherry-pick-2.2

#1341 Revert "bump tipb and kvproto to latest master"
  tikv-client/scripts/proto.sh
  tikv-client/src/main/java/com/pingcap/tikv/meta/TiDAGRequest.java
  tikv-client/src/main/java/com/pingcap/tikv/operation/iterator/CoprocessorIterator.java
  tikv-client/src/main/java/com/pingcap/tikv/operation/iterator/DAGIterator.java
  tikv-client/src/main/java/com/pingcap/tikv/region/RegionStoreClient.java
  tikv-client/src/test/java/com/pingcap/tikv/KVMockServer.java
  tikv-client/src/test/java/com/pingcap/tikv/RegionStoreClientTest.java
Labels: DNM
