Repository pingcap/tispark, pull requests merged in 2020-04, with the labels that each got.

#1391 support tidb-4.0
  .ci/integration_test.groovy
  config/pd-4.0.toml
  config/tidb-4.0.toml
  config/tikv-4.0.toml
  core/src/main/scala/org/apache/spark/sql/TiStrategy.scala
  docker-compose-4.0.yaml
  tikv-client/src/main/java/com/pingcap/tikv/meta/TiDAGRequest.java
  tikv-client/src/main/java/com/pingcap/tikv/types/BytesType.java
Labels: needs-cherry-pick-2.1, needs-cherry-pick-2.2

#1395 simplify WrappedEncodedRow
  core/src/main/scala/com/pingcap/tispark/TiBatchWrite.scala
Labels: needs-cherry-pick-2.2

#1401 implement hashCode in wrapped encoded row
  core/src/main/scala/com/pingcap/tispark/TiBatchWrite.scala
Labels: needs-cherry-pick-2.2

#1403 fix increasing pd connections bug
  core/src/main/scala/org/apache/spark/sql/TiExtensions.scala
Labels: needs-cherry-pick-master

#1408 bump kvproto to v4.0.0-rc
  tikv-client/pom.xml
  tikv-client/scripts/proto.sh
Labels: needs-cherry-pick-2.1
