Repository pingcap/tispark, pull requests merged in 2020-10, with the labels that each got.

#1639 Fix covering index error when alter-primary-key is enabled
  tikv-client/src/main/java/com/pingcap/tikv/meta/TiDAGRequest.java
Labels: needs-cherry-pick-2.3

#1644 Fix alter primary key for write
  .ci/integration_test.groovy
  config/tidb-4.0.toml
  config/tidb.toml
  core/src/main/scala/com/pingcap/tispark/write/TiBatchWriteTable.scala
  core/src/test/scala/com/pingcap/tispark/datasource/AutoIncrementSuite.scala
  core/src/test/scala/com/pingcap/tispark/datasource/ColumnMappingSuite.scala
  core/src/test/scala/org/apache/spark/sql/BaseTiSparkTest.scala
  core/src/test/scala/org/apache/spark/sql/catalyst/plans/statistics/StatisticsTestSuite.scala
  tikv-client/src/main/java/com/pingcap/tikv/TiDBJDBCClient.java
  tikv-client/src/main/java/com/pingcap/tikv/allocator/RowIDAllocator.java
Labels: needs-cherry-pick-2.3

#1645 [cherry pick] Fix alter primary key for write
  .ci/integration_test.groovy
  config/tidb-4.0.toml
  config/tidb.toml
  core/src/main/scala/com/pingcap/tispark/write/TiBatchWriteTable.scala
  core/src/test/scala/com/pingcap/tispark/datasource/AutoIncrementSuite.scala
  core/src/test/scala/com/pingcap/tispark/datasource/ColumnMappingSuite.scala
  core/src/test/scala/org/apache/spark/sql/BaseTiSparkTest.scala
  core/src/test/scala/org/apache/spark/sql/catalyst/plans/statistics/StatisticsTestSuite.scala
  tikv-client/src/main/java/com/pingcap/tikv/TiDBJDBCClient.java
  tikv-client/src/main/java/com/pingcap/tikv/allocator/RowIDAllocator.java
Labels: CHERRY-PICK

#1646 release tispark-2.3.6
  CHANGELOG.md
  README.md
Labels: needs-cherry-pick-2.3

#1649 support invisible index
  core/src/test/scala/org/apache/spark/sql/InvisibleIndexSuite.scala
  tikv-client/src/main/java/com/pingcap/tikv/meta/TiIndexInfo.java
  tikv-client/src/main/java/com/pingcap/tikv/meta/TiTableInfo.java
  tikv-client/src/test/java/com/pingcap/tikv/meta/MetaUtils.java
  tikv-client/src/test/java/com/pingcap/tikv/predicates/TiKVScanAnalyzerTest.java
Labels: needs-cherry-pick-2.4, tidb-5.0

#1648 upgrade spark to 2.4.6
  core/src/test/scala/org/apache/spark/sql/benchmark/TPCHQuerySuite.scala
  docs/userguide.md
  pom.xml
  spark-wrapper/spark-2.4/pom.xml
Labels: needs-cherry-pick-2.4

#1655 enable user provided auto increment value in update mode
  core/src/main/scala/com/pingcap/tispark/write/TiBatchWriteTable.scala
  core/src/test/scala/com/pingcap/tispark/datasource/AutoIncrementSuite.scala
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4

#1660 BatchWrite: fix initial ttl expired
  core/src/main/scala/com/pingcap/tispark/write/TiBatchWrite.scala
  core/src/main/scala/com/pingcap/tispark/write/TiDBOptions.scala
  core/src/test/scala/com/pingcap/tispark/ttl/InitialTTLExpiredSuite.scala
  tikv-client/src/main/java/com/pingcap/tikv/TTLManager.java
Labels: needs-cherry-pick-2.4, needs-cherry-pick-master

#1664 add parameter document: bytesPerRegion
  docs/datasource_api_userguide.md
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4

#1661 BatchWrite: fix commit ts expired
  core/src/main/scala/com/pingcap/tispark/write/TiBatchWrite.scala
  core/src/main/scala/com/pingcap/tispark/write/TiDBOptions.scala
Labels: needs-cherry-pick-2.4, needs-cherry-pick-master

#1670 release-2.3.7
  CHANGELOG.md
  README.md
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4

#1657 fix negative column id when there are more than 128 columns
  tikv-client/src/main/java/com/pingcap/tikv/codec/RowEncoderV2.java
  tikv-client/src/main/java/com/pingcap/tikv/codec/RowV2.java
Labels: first-time-contributor, needs-cherry-pick-2.3, needs-cherry-pick-2.4

#1656 fix wrong conversion from LocalDate to days since UNIX epoch
  tikv-client/src/main/java/com/pingcap/tikv/columnar/TiBlockColumnVector.java
  tikv-client/src/main/java/com/pingcap/tikv/columnar/TiChunkColumnVector.java
  tikv-client/src/main/java/com/pingcap/tikv/types/AbstractDateTimeType.java
  tikv-client/src/main/java/com/pingcap/tikv/types/DateType.java
Labels: first-time-contributor, needs-cherry-pick-2.3, needs-cherry-pick-2.4

#1677 fix TiSession Close bug
  tikv-client/src/main/java/com/pingcap/tikv/TiSession.java
Labels: needs-cherry-pick-2.4, needs-cherry-pick-master

#1681 optimize region split number in small data size
  core/src/main/scala/com/pingcap/tispark/write/TiBatchWrite.scala
  core/src/main/scala/com/pingcap/tispark/write/TiDBOptions.scala
Labels: needs-cherry-pick-2.4, needs-cherry-pick-master

#1694 BatchWrite: fix auto increment column not primary key
  core/src/test/scala/com/pingcap/tispark/datasource/AutoIncrementSuite.scala
  tikv-client/src/main/java/com/pingcap/tikv/meta/TiTableInfo.java
Labels: needs-cherry-pick-2.4, needs-cherry-pick-master

#1695 BatchWrite: add more log for exception
  core/src/main/scala/com/pingcap/tispark/write/TiBatchWriteTable.scala
Labels: needs-cherry-pick-2.4, needs-cherry-pick-master

#1703 Fix incorrect date type value when timezone is set
  core/src/test/scala/org/apache/spark/sql/IssueTestSuite.scala
  tikv-client/src/main/java/com/pingcap/tikv/columnar/TiBlockColumnVector.java
  tikv-client/src/main/java/com/pingcap/tikv/columnar/TiChunkColumnVector.java
  tikv-client/src/main/java/com/pingcap/tikv/types/AbstractDateTimeType.java
  tikv-client/src/main/java/com/pingcap/tikv/types/DateType.java
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4

#1706 release tispark-2.3.8
  CHANGELOG.md
  README.md
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4

#1709 Fix typo in DateTime calculation
  tikv-client/src/main/java/com/pingcap/tikv/types/AbstractDateTimeType.java
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4

#1712 fix LockTimeoutSuite
  core/src/main/scala/com/pingcap/tispark/write/TiBatchWrite.scala
  core/src/main/scala/com/pingcap/tispark/write/TiDBOptions.scala
  core/src/test/scala/com/pingcap/tispark/ttl/LockTimeoutSuite.scala
Labels: needs-cherry-pick-2.4, needs-cherry-pick-master

#1718 release tispark-2.3.9
  CHANGELOG.md
  README.md
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4
