Repository pingcap/tispark, pull requests merged in 2020-11, with the labels that each got.

#1723 Fix string insert overflow check
  core/src/test/scala/com/pingcap/tispark/overflow/StringOverflowSuite.scala
  tikv-client/src/main/java/com/pingcap/tikv/types/StringType.java
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4

#1729 BatchWrite: add parameter maxRegionSplitNum
  core/src/main/scala/com/pingcap/tispark/write/TiBatchWrite.scala
  core/src/main/scala/com/pingcap/tispark/write/TiDBOptions.scala
Labels: needs-cherry-pick-2.4, needs-cherry-pick-master

#1737 fix maven-shade-plugin relocation cannot handle folder name with dot
  assembly/src/main/assembly/assembly.xml
  core/src/main/scala/com/pingcap/tispark/utils/ReflectionUtil.scala
Labels: needs-cherry-pick-2.4

#1748 release tispark-2.3.10
  CHANGELOG.md
  README.md
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4

#1755 make test stable
  core/src/test/scala/com/pingcap/tispark/index/LineItemSuite.scala
Labels: needs-cherry-pick-2.4, needs-cherry-pick-master

#1751 Fix enum insert with trailing spaces
  core/src/main/scala/com/pingcap/tispark/TiDBUtils.scala
  core/src/test/scala/com/pingcap/tispark/convert/ToBitSuite.scala
  core/src/test/scala/com/pingcap/tispark/convert/ToBytesSuite.scala
  core/src/test/scala/com/pingcap/tispark/convert/ToDateSuite.scala
  core/src/test/scala/com/pingcap/tispark/convert/ToDateTimeSuite.scala
  core/src/test/scala/com/pingcap/tispark/convert/ToDecimalSuite.scala
  core/src/test/scala/com/pingcap/tispark/convert/ToEnumSuite.scala
  core/src/test/scala/com/pingcap/tispark/convert/ToRealSuite.scala
  core/src/test/scala/com/pingcap/tispark/convert/ToSignedSuite.scala
  core/src/test/scala/com/pingcap/tispark/convert/ToStringSuite.scala
  core/src/test/scala/com/pingcap/tispark/convert/ToTimestampSuite.scala
  core/src/test/scala/com/pingcap/tispark/convert/ToUnsignedSuite.scala
  core/src/test/scala/com/pingcap/tispark/datasource/BaseBatchWriteWithoutDropTableTest.scala
  core/src/test/scala/com/pingcap/tispark/datasource/BaseDataSourceTest.scala
  core/src/test/scala/com/pingcap/tispark/datatype/BatchWriteDataTypeSuite.scala
  core/src/test/scala/com/pingcap/tispark/overflow/DecimalOverflowSuite.scala
  core/src/test/scala/com/pingcap/tispark/overflow/StringOverflowSuite.scala
  core/src/test/scala/org/apache/spark/sql/BaseTiSparkTest.scala
  core/src/test/scala/org/apache/spark/sql/insertion/BatchWritePkSuite.scala
  core/src/test/scala/org/apache/spark/sql/insertion/BatchWriteUniqueIndexSuite.scala
  tikv-client/src/main/java/com/pingcap/tikv/codec/Codec.java
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4

#1770 fix column name compare bug
  core/src/main/scala/com/pingcap/tispark/write/TiBatchWriteTable.scala
  core/src/test/scala/com/pingcap/tispark/datasource/AutoIncrementSuite.scala
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4

#1774 add document for writing to json type
  docs/datasource_api_userguide.md
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4

#1778 add test for integer conversion
  core/src/test/scala/com/pingcap/tispark/BatchWriteIssueSuite.scala
Labels: needs-cherry-pick-2.4

#1780 add conversion from java.math.BigDecimal to Long
  core/src/test/scala/com/pingcap/tispark/BatchWriteIssueSuite.scala
  tikv-client/src/main/java/com/pingcap/tikv/types/Converter.java
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4

#1783 fix Table default.st1 already exists
  core/src/test/scala/com/pingcap/tispark/BatchWriteIssueSuite.scala
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4

#1786 BatchWrite: support insert null on auto increment column
  core/src/main/scala/com/pingcap/tispark/write/TiBatchWriteTable.scala
  core/src/test/scala/com/pingcap/tispark/datasource/AutoIncrementSuite.scala
Labels: needs-cherry-pick-2.4, needs-cherry-pick-master

#1790 disable year type index scan
  core/src/test/scala/org/apache/spark/sql/IssueTestSuite.scala
  tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java
Labels: needs-cherry-pick-2.4, needs-cherry-pick-master

#1768 do not retry for some key error
  tikv-client/src/main/java/com/pingcap/tikv/exception/KeyException.java
  tikv-client/src/main/java/com/pingcap/tikv/region/RegionStoreClient.java
  tikv-client/src/main/java/com/pingcap/tikv/txn/AbstractLockResolverClient.java
  tikv-client/src/main/java/com/pingcap/tikv/txn/TxnKVClient.java
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4

#1802 update idleMinutes to 10
  .ci/integration_test.groovy
Labels: needs-cherry-pick-2.1, needs-cherry-pick-2.3, needs-cherry-pick-2.4

#1798 support log desensitization
  .ci/log4j-ci.properties
  core/src/main/scala/com/pingcap/tispark/write/SerializableKey.scala
  tikv-client/src/main/java/com/pingcap/tikv/PDClient.java
  tikv-client/src/main/java/com/pingcap/tikv/TTLManager.java
  tikv-client/src/main/java/com/pingcap/tikv/TwoPhaseCommitter.java
  tikv-client/src/main/java/com/pingcap/tikv/exception/WriteConflictException.java
  tikv-client/src/main/java/com/pingcap/tikv/key/Key.java
  tikv-client/src/main/java/com/pingcap/tikv/key/TypedKey.java
  tikv-client/src/main/java/com/pingcap/tikv/meta/TiDAGRequest.java
  tikv-client/src/main/java/com/pingcap/tikv/operation/KVErrorHandler.java
  tikv-client/src/main/java/com/pingcap/tikv/region/RegionManager.java
  tikv-client/src/main/java/com/pingcap/tikv/region/TiRegion.java
  tikv-client/src/main/java/com/pingcap/tikv/row/ObjectRowImpl.java
  tikv-client/src/main/java/com/pingcap/tikv/util/LogDesensitization.java
  tikv-client/src/test/java/com/pingcap/tikv/key/CompoundKeyTest.java
  tikv-client/src/test/java/com/pingcap/tikv/key/IndexKeyTest.java
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4

#1807 make ci test stable
  core/src/test/scala/com/pingcap/tispark/index/LineItemSuite.scala
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4

#1812 make regression test stable
  core/src/test/scala/com/pingcap/tispark/index/LineItemSuite.scala
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4

#1810 support read from table with expression index
  README.md
  core/src/test/scala/com/pingcap/tispark/datasource/ExceptionTestSuite.scala
  core/src/test/scala/org/apache/spark/sql/BaseTiSparkTest.scala
  core/src/test/scala/org/apache/spark/sql/ExpressionIndexSuite.scala
  tikv-client/src/main/java/com/pingcap/tikv/meta/TiColumnInfo.java
  tikv-client/src/main/java/com/pingcap/tikv/meta/TiTableInfo.java
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4
