Repository pingcap/tispark, pull requests merged in 2020-01, with the labels that each got.

#1347 Fix time zone tests with Spark+JDBC
  core/src/test/scala/com/pingcap/tispark/datasource/BaseDataSourceTest.scala
  core/src/test/scala/org/apache/spark/sql/BaseTiSparkTest.scala
  core/src/test/scala/org/apache/spark/sql/test/SharedSQLContext.scala
Labels: needs-cherry-pick-2.1, needs-cherry-pick-2.2

#1345 shade io.opencensus to resolve grpc conflict
  tikv-client/pom.xml
Labels: needs-cherry-pick-2.1, needs-cherry-pick-2.2

#1350 [cherry-pick] Fix time zone tests with Spark+JDBC (#1347)
  core/src/test/scala/org/apache/spark/sql/BaseTiSparkSuite.scala
  core/src/test/scala/org/apache/spark/sql/test/SharedSQLContext.scala
Labels: CHERRY-PICK

#1360 add variable check before setting tidb_row_format_version
  core/src/test/scala/org/apache/spark/sql/test/SharedSQLContext.scala
Labels: needs-cherry-pick-2.1, needs-cherry-pick-2.2

#1364 Fix DateTime test failure on CI
  core/src/main/scala/org/apache/spark/sql/catalyst/expressions/ExprUtils.scala
  tikv-client/src/main/java/com/pingcap/tikv/expression/AggregateFunction.java
Labels: needs-cherry-pick-2.1, needs-cherry-pick-2.2

#1343 Support enum and set in test generation
  core/src/test/scala/org/apache/spark/sql/BaseTestGenerationSpec.scala
  core/src/test/scala/org/apache/spark/sql/BaseTiSparkTest.scala
  core/src/test/scala/org/apache/spark/sql/insertion/BaseEnumerateDataTypesTestSpec.scala
  core/src/test/scala/org/apache/spark/sql/test/generator/ColumnValueGenerator.scala
  core/src/test/scala/org/apache/spark/sql/test/generator/DataType.scala
  core/src/test/scala/org/apache/spark/sql/test/generator/GeneratorUtils.scala
  core/src/test/scala/org/apache/spark/sql/test/generator/Schema.scala
  core/src/test/scala/org/apache/spark/sql/test/generator/TestDataGenerator.scala
  core/src/test/scala/org/apache/spark/sql/types/DataTypeNormalSuite.scala
  core/src/test/scala/org/apache/spark/sql/types/GenerateMultiColumnDataTypeTestAction.scala
  core/src/test/scala/org/apache/spark/sql/types/GenerateUnitDataTypeTestAction.scala
  core/src/test/scala/org/apache/spark/sql/types/MultiColumnDataTypeSuite.scala
  core/src/test/scala/org/apache/spark/sql/types/pk/GenerateMultiColumnPKDataTypeTestAction.scala
  core/src/test/scala/org/apache/spark/sql/types/pk/MultiColumnPKDataTypeSuites.scala
Labels: needs-cherry-pick-2.2

#1354 fix parition table isn't shown in show command
  core/src/main/scala/org/apache/spark/sql/execution/command/tables.scala
  core/src/test/scala/org/apache/spark/sql/catalyst/catalog/CatalogTestSuite.scala
Labels: needs-cherry-pick-2.1, needs-cherry-pick-2.2

#1365 Fix Statistics test failure on CI
  config/tidb.toml
Labels: needs-cherry-pick-2.1, needs-cherry-pick-2.2

#1369 remove log4j dependency
  core/src/main/scala/com/pingcap/tispark/listener/CacheInvalidateListener.scala
  core/src/main/scala/org/apache/spark/sql/execution/CoprocessorRDD.scala
  core/src/test/scala/org/apache/spark/sql/test/Utils.scala
  tikv-client/pom.xml
  tikv-client/src/main/java/com/pingcap/tikv/AbstractGRPCClient.java
  tikv-client/src/main/java/com/pingcap/tikv/KVClient.java
  tikv-client/src/main/java/com/pingcap/tikv/catalog/Catalog.java
  tikv-client/src/main/java/com/pingcap/tikv/catalog/CatalogTransaction.java
  tikv-client/src/main/java/com/pingcap/tikv/operation/KVErrorHandler.java
  tikv-client/src/main/java/com/pingcap/tikv/operation/PDErrorHandler.java
  tikv-client/src/main/java/com/pingcap/tikv/operation/iterator/ConcreteScanIterator.java
  tikv-client/src/main/java/com/pingcap/tikv/region/RegionManager.java
  tikv-client/src/main/java/com/pingcap/tikv/region/RegionStoreClient.java
  tikv-client/src/main/java/com/pingcap/tikv/txn/LockResolverClient.java
  tikv-client/src/main/java/com/pingcap/tikv/util/ConcreteBackOffer.java
  tikv-client/src/test/java/com/pingcap/tikv/txn/LockResolverRCTest.java
  tikv-client/src/test/java/com/pingcap/tikv/txn/LockResolverSITest.java
  tikv-client/src/test/java/com/pingcap/tikv/txn/LockResolverTest.java
Labels: needs-cherry-pick-2.1, needs-cherry-pick-2.2

#1372 fix test compatibility
  core/src/test/scala/org/apache/spark/sql/PartitionTableSuite.scala
Labels: needs-cherry-pick-2.1, needs-cherry-pick-2.2
