Repository pingcap/tispark, pull requests merged in 2020-12, with the labels that each got.

#1816 ignore lineitem batchwrite test
  core/src/test/scala/com/pingcap/tispark/index/LineItemSuite.scala
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4

#1819 add document netty oom
  docs/userguide.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-2.3, needs-cherry-pick-2.4

#1823 fix document typo
  docs/userguide.md
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4

#1822 add document spark.sql.runSQLOnFiles
  README.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-2.3, needs-cherry-pick-2.4

#1829 add document show create table
  README.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-2.3, needs-cherry-pick-2.4

#1833 Using the style of {db}.{table}.{colname} in the condition is not sup…
  README.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-2.3, needs-cherry-pick-2.4

#1837 support auto_random column
  core/src/main/scala/com/pingcap/tispark/write/TiBatchWriteTable.scala
  core/src/test/scala/com/pingcap/tispark/datasource/AutoRandomSuite.scala
  tikv-client/src/main/java/com/pingcap/tikv/meta/TiTableInfo.java
  tikv-client/src/test/java/com/pingcap/tikv/meta/MetaUtils.java
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4

#1840 fix select count where values contains null
  core/src/main/scala/org/apache/spark/sql/catalyst/expressions/TiExprUtils.scala
  core/src/test/scala/org/apache/spark/sql/IssueTestSuite.scala
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4

#1843 add test: select count(a, b) with null values
  core/src/test/scala/org/apache/spark/sql/IssueTestSuite.scala
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4

#1846 ignore test lock on tiflash: not expired
  core/src/test/scala/com/pingcap/tispark/tiflash/TiFlashSuite.scala
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4

#1849 fix Too many keys specified; max 64 keys allowed
  config/tidb-4.0.toml
  core/src/test/scala/com/pingcap/tispark/datatype/DecimalTypeSuite.scala
  core/src/test/scala/org/apache/spark/sql/IssueTestSuite.scala
  core/src/test/scala/org/apache/spark/sql/catalyst/plans/statistics/StatisticsTestSuite.scala
  core/src/test/scala/org/apache/spark/sql/expression/LikeTestSuite.scala
  core/src/test/scala/org/apache/spark/sql/expression/index/Between0Suite.scala
  core/src/test/scala/org/apache/spark/sql/expression/index/ComprehensiveSuite.scala
  core/src/test/scala/org/apache/spark/sql/expression/index/CoveringIndex0Suite.scala
  core/src/test/scala/org/apache/spark/sql/expression/index/InTest0Suite.scala
  core/src/test/scala/org/apache/spark/sql/expression/index/Join0Suite.scala
  core/src/test/scala/org/apache/spark/sql/expression/index/Special0Suite.scala
  core/src/test/scala/org/apache/spark/sql/test/SharedSQLContext.scala
Labels: needs-cherry-pick-2.4

#1851 null in aggregration it not supported
  README.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-2.3, needs-cherry-pick-2.4

#1857 ignore text type overflow test
  core/src/test/scala/com/pingcap/tispark/overflow/StringOverflowSuite.scala
Labels: needs-cherry-pick-2.4

#1856 add retry in RowIDAllocator
  core/src/test/scala/com/pingcap/tispark/concurrency/WriteWriteConflictSuite.scala
  tikv-client/src/main/java/com/pingcap/tikv/allocator/RowIDAllocator.java
  tikv-client/src/main/java/com/pingcap/tikv/util/BackOffer.java
Labels: needs-cherry-pick-2.4, needs-cherry-pick-master

#1863 fix tispark overflow test
  tikv-client/src/main/java/com/pingcap/tikv/allocator/RowIDAllocator.java
Labels: needs-cherry-pick-2.4, needs-cherry-pick-master

#1867 fix overflow when convert big MyDecimal to BigDecimal
  tikv-client/src/main/java/com/pingcap/tikv/codec/MyDecimal.java
  tikv-client/src/test/java/com/pingcap/tikv/codec/MyDecimalTest.java
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4

#1868 txn: fix the resolved txn status cache for pessimistic txn
  tikv-client/src/main/java/com/pingcap/tikv/txn/LockResolverClientV4.java
Labels: needs-cherry-pick-2.4, needs-cherry-pick-master

#1871 txn: fix the resolved txn status cache for pessimistic txn #1868
  tikv-client/src/main/java/com/pingcap/tikv/txn/LockResolverClientV4.java
Labels: needs-cherry-pick-2.4

#1874 release tispark-2.3.11
  CHANGELOG.md
  README.md
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4

#1878 add doc for garbled chinese characters problem
  docs/userguide.md
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4
