Repository pingcap/tispark, pull requests merged in 2021-03, with the labels that each got.

#1919 disable index scan for clustered index table
  core/src/test/scala/org/apache/spark/sql/BaseTiSparkTest.scala
  core/src/test/scala/org/apache/spark/sql/IssueTestSuite.scala
  tikv-client/src/main/java/com/pingcap/tikv/TiDBJDBCClient.java
  tikv-client/src/main/java/com/pingcap/tikv/meta/TiDAGRequest.java
  tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java
Labels: needs-cherry-pick-2.4

#1923 Disable index scan on partition table
  tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4

#1927 disable IndexScan for clustered index
  tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java
Labels: needs-cherry-pick-2.4

#1929 release tispark 2.3.13
  CHANGELOG.md
  README.md
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4

#1944 ignore clustered index test if tidb does not support
  core/src/test/scala/org/apache/spark/sql/clustered/IndexScan0Suite.scala
  core/src/test/scala/org/apache/spark/sql/clustered/IndexScan1Suite.scala
  core/src/test/scala/org/apache/spark/sql/clustered/TableScan0Suite.scala
  core/src/test/scala/org/apache/spark/sql/clustered/TableScan1Suite.scala
Labels: needs-cherry-pick-2.4

#1946 fix WriteWriteConflictSuite
  core/src/test/scala/com/pingcap/tispark/concurrency/WriteWriteConflictSuite.scala
Labels: needs-cherry-pick-2.3, needs-cherry-pick-master

#1949 fix test with tidb does not support clustered index
  core/src/test/scala/org/apache/spark/sql/clustered/ClusteredIndexTest.scala
Labels: needs-cherry-pick-2.4

#1953 fix unit test: convert real
  core/src/test/scala/com/pingcap/tispark/convert/ToRealSuite.scala
Labels: needs-cherry-pick-2.4, needs-cherry-pick-master

#1956 fix unit test: NPE when decoding datetime,date,timestamp
  core/src/test/scala/org/apache/spark/sql/IssueTestSuite.scala
Labels: needs-cherry-pick-2.4, needs-cherry-pick-master

#1952 fix GregorianCalendar
  core/src/test/scala/org/apache/spark/sql/IssueTestSuite.scala
  tikv-client/src/main/java/com/pingcap/tikv/columnar/TiBlockColumnVector.java
  tikv-client/src/main/java/com/pingcap/tikv/columnar/TiChunkColumnVector.java
  tikv-client/src/main/java/com/pingcap/tikv/types/DateType.java
Labels: needs-cherry-pick-2.4

#1961 continue to fix GregorianCalendar
  core/src/test/scala/org/apache/spark/sql/IssueTestSuite.scala
  tikv-client/src/main/java/com/pingcap/tikv/types/DateType.java
Labels: needs-cherry-pick-2.3

#1966 fix tiflash timestamp pushdown bug
  tikv-client/src/main/java/com/pingcap/tikv/expression/visitor/ProtoConverter.java
Labels: needs-cherry-pick-2.4, needs-cherry-pick-master

#1969 let test success because of a tiflash bug
  .ci/tidb_config-for-tiflash-test.properties
  core/src/test/scala/org/apache/spark/sql/IssueTestSuite.scala
  core/src/test/scala/org/apache/spark/sql/test/SharedSQLContext.scala
Labels: needs-cherry-pick-2.3, needs-cherry-pick-master

#1972 fix tidb_enable_clustered_index only support global variable
  core/src/main/scala/com/pingcap/tispark/write/TiBatchWriteTable.scala
  core/src/test/scala/org/apache/spark/sql/IssueTestSuite.scala
  core/src/test/scala/org/apache/spark/sql/clustered/ClusteredIndexTest.scala
  core/src/test/scala/org/apache/spark/sql/test/SharedSQLContext.scala
Labels: needs-cherry-pick-2.4

#1974 fix tidb_enable_clustered_index test with tidb-4.0
  core/src/test/scala/org/apache/spark/sql/BaseTiSparkTest.scala
  core/src/test/scala/org/apache/spark/sql/test/SharedSQLContext.scala
Labels: needs-cherry-pick-2.4

#1976 update userguide.md: add partition syntax guide.
  docs/userguide.md
Labels: needs-cherry-pick-2.1, needs-cherry-pick-2.3, needs-cherry-pick-2.4, needs-cherry-pick-master

#1978 fix regresstion test: AutoIncrementSuite
  core/src/test/scala/com/pingcap/tispark/datasource/AutoIncrementSuite.scala
  core/src/test/scala/com/pingcap/tispark/datasource/ColumnMappingSuite.scala
  core/src/test/scala/org/apache/spark/sql/IssueTestSuite.scala
  core/src/test/scala/org/apache/spark/sql/catalyst/plans/statistics/StatisticsTestSuite.scala
  core/src/test/scala/org/apache/spark/sql/clustered/ClusteredIndexTest.scala
  core/src/test/scala/org/apache/spark/sql/test/SharedSQLContext.scala
Labels: needs-cherry-pick-2.4

#1983 print schema in test
  core/src/test/scala/org/apache/spark/sql/test/SharedSQLContext.scala
Labels: needs-cherry-pick-2.4

#1986 fix large column number + double read bug (#1985)
  core/src/main/scala/com/pingcap/tispark/TiDBRelation.scala
  core/src/main/scala/org/apache/spark/sql/execution/CoprocessorRDD.scala
  core/src/main/scala/org/apache/spark/sql/tispark/TiHandleRDD.scala
Labels: CHERRY-PICK

#1988 add nightly download link
  README.md
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4
