Repository pingcap/tispark, pull requests merged in 2021-09, with the labels that each got.

#2101 fix region split: region split key should be a vaild key
  tikv-client/src/main/java/com/pingcap/tikv/KVClient.java
  tikv-client/src/main/java/com/pingcap/tikv/TiSession.java
Labels: needs-cherry-pick-master, needs-cherry-pick-2.3

#2106 Optimize region cache miss
  core/src/main/scala/com/pingcap/tispark/MetaManager.scala
  core/src/main/scala/com/pingcap/tispark/TiDBRelation.scala
  core/src/main/scala/com/pingcap/tispark/handler/CacheInvalidateEventHandler.scala
  core/src/main/scala/com/pingcap/tispark/statistics/StatisticsManager.scala
  core/src/main/scala/com/pingcap/tispark/utils/TiUtil.scala
  core/src/test/scala/org/apache/spark/sql/catalyst/plans/statistics/StatisticsTestSuite.scala
  tikv-client/src/main/java/com/pingcap/tikv/KVClient.java
  tikv-client/src/main/java/com/pingcap/tikv/TiConfiguration.java
  tikv-client/src/main/java/com/pingcap/tikv/allocator/RowIDAllocator.java
  tikv-client/src/main/java/com/pingcap/tikv/catalog/Catalog.java
  tikv-client/src/main/java/com/pingcap/tikv/event/CacheInvalidateEvent.java
  tikv-client/src/main/java/com/pingcap/tikv/operation/KVErrorHandler.java
  tikv-client/src/main/java/com/pingcap/tikv/operation/iterator/ConcreteScanIterator.java
  tikv-client/src/main/java/com/pingcap/tikv/operation/iterator/DAGIterator.java
  tikv-client/src/main/java/com/pingcap/tikv/operation/iterator/ScanIterator.java
  tikv-client/src/main/java/com/pingcap/tikv/region/RegionManager.java
  tikv-client/src/main/java/com/pingcap/tikv/region/RegionStoreClient.java
  tikv-client/src/main/java/com/pingcap/tikv/region/TiRegion.java
  tikv-client/src/main/java/com/pingcap/tikv/txn/Lock.java
  tikv-client/src/test/java/com/pingcap/tikv/RegionManagerTest.java
  tikv-client/src/test/java/com/pingcap/tikv/RegionStoreClientTest.java
  tikv-client/src/test/java/com/pingcap/tikv/util/RangeSplitterTest.java
  tikv-client/src/test/java/com/pingcap/tikv/util/ReflectionWrapper.java
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4

#2108 Cherry pick #2106 release-2.3
  core/src/main/scala/com/pingcap/tispark/MetaManager.scala
  core/src/main/scala/com/pingcap/tispark/TiDBRelation.scala
  core/src/main/scala/com/pingcap/tispark/handler/CacheInvalidateEventHandler.scala
  core/src/main/scala/com/pingcap/tispark/statistics/StatisticsManager.scala
  core/src/main/scala/com/pingcap/tispark/utils/TiUtil.scala
  core/src/test/scala/org/apache/spark/sql/catalyst/plans/statistics/StatisticsTestSuite.scala
  tikv-client/src/main/java/com/pingcap/tikv/KVClient.java
  tikv-client/src/main/java/com/pingcap/tikv/TiConfiguration.java
  tikv-client/src/main/java/com/pingcap/tikv/allocator/RowIDAllocator.java
  tikv-client/src/main/java/com/pingcap/tikv/catalog/Catalog.java
  tikv-client/src/main/java/com/pingcap/tikv/event/CacheInvalidateEvent.java
  tikv-client/src/main/java/com/pingcap/tikv/operation/KVErrorHandler.java
  tikv-client/src/main/java/com/pingcap/tikv/operation/iterator/ConcreteScanIterator.java
  tikv-client/src/main/java/com/pingcap/tikv/operation/iterator/DAGIterator.java
  tikv-client/src/main/java/com/pingcap/tikv/operation/iterator/ScanIterator.java
  tikv-client/src/main/java/com/pingcap/tikv/region/RegionManager.java
  tikv-client/src/main/java/com/pingcap/tikv/region/RegionStoreClient.java
  tikv-client/src/main/java/com/pingcap/tikv/region/TiRegion.java
  tikv-client/src/main/java/com/pingcap/tikv/txn/Lock.java
  tikv-client/src/test/java/com/pingcap/tikv/RegionManagerTest.java
  tikv-client/src/test/java/com/pingcap/tikv/RegionStoreClientTest.java
  tikv-client/src/test/java/com/pingcap/tikv/util/RangeSplitterTest.java
  tikv-client/src/test/java/com/pingcap/tikv/util/ReflectionWrapper.java
Labels: CHERRY-PICK

#2110 fix catalog test
  tikv-client/src/test/java/com/pingcap/tikv/catalog/CatalogTest.java
  tikv-client/src/test/java/com/pingcap/tikv/util/ReflectionWrapper.java
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4

#2104 Fix datetime shift before year 1582
  core/src/test/scala/com/pingcap/tispark/datatype/BatchWriteDataTypeSuite.scala
  tikv-client/src/main/java/com/pingcap/tikv/ExtendedDateTime.java
  tikv-client/src/main/java/com/pingcap/tikv/codec/Codec.java
  tikv-client/src/main/java/com/pingcap/tikv/codec/RowEncoderV2.java
  tikv-client/src/main/java/com/pingcap/tikv/columnar/TiBlockColumnVector.java
  tikv-client/src/main/java/com/pingcap/tikv/columnar/TiChunkColumnVector.java
  tikv-client/src/main/java/com/pingcap/tikv/columnar/TiCoreTime.java
  tikv-client/src/main/java/com/pingcap/tikv/types/Converter.java
  tikv-client/src/test/java/com/pingcap/tikv/codec/TableCodecV2Test.java
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4

#2114 Close TTLManager before creating a new one
  core/src/main/scala/com/pingcap/tispark/write/TiBatchWrite.scala
  tikv-client/src/main/java/com/pingcap/tikv/TTLManager.java
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4

#2120 Fix channel shut-downed due to ping failure
  core/src/test/scala/org/apache/spark/sql/SequenceTestSuite.scala
  core/src/test/scala/org/apache/spark/sql/ViewTestSuite.scala
  core/src/test/scala/org/apache/spark/sql/types/BaseRandomDataTypeTest.scala
  tikv-client/src/main/java/com/pingcap/tikv/util/ChannelFactory.java
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4

#2123 Close PDClient without closing channel factory
  tikv-client/src/main/java/com/pingcap/tikv/PDClient.java
  tikv-client/src/main/java/com/pingcap/tikv/TiSession.java
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4

#2115 Fix datetime shift before year 1582 (#2104)
  core/src/test/scala/com/pingcap/tispark/datatype/BatchWriteDataTypeSuite.scala
  tikv-client/src/main/java/com/pingcap/tikv/ExtendedDateTime.java
  tikv-client/src/main/java/com/pingcap/tikv/codec/Codec.java
  tikv-client/src/main/java/com/pingcap/tikv/codec/RowEncoderV2.java
  tikv-client/src/main/java/com/pingcap/tikv/columnar/TiBlockColumnVector.java
  tikv-client/src/main/java/com/pingcap/tikv/columnar/TiChunkColumnVector.java
  tikv-client/src/main/java/com/pingcap/tikv/columnar/TiCoreTime.java
  tikv-client/src/main/java/com/pingcap/tikv/types/Converter.java
  tikv-client/src/test/java/com/pingcap/tikv/codec/TableCodecV2Test.java
Labels: CHERRY-PICK

#2116 Fix datetime shift before year 1582 (#2104)
  core/src/test/scala/com/pingcap/tispark/datatype/BatchWriteDataTypeSuite.scala
  tikv-client/src/main/java/com/pingcap/tikv/ExtendedDateTime.java
  tikv-client/src/main/java/com/pingcap/tikv/codec/Codec.java
  tikv-client/src/main/java/com/pingcap/tikv/codec/RowEncoderV2.java
  tikv-client/src/main/java/com/pingcap/tikv/columnar/TiBlockColumnVector.java
  tikv-client/src/main/java/com/pingcap/tikv/columnar/TiChunkColumnVector.java
  tikv-client/src/main/java/com/pingcap/tikv/columnar/TiCoreTime.java
  tikv-client/src/main/java/com/pingcap/tikv/types/Converter.java
  tikv-client/src/test/java/com/pingcap/tikv/codec/TableCodecV2Test.java
Labels: CHERRY-PICK

#2119 Set up codeql workflow
  .github/workflows/codeql-analysis.yml
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4

#2129 Enable test enum with empty sql mode
  core/src/test/scala/org/apache/spark/sql/IssueTestSuite.scala
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4

#2127 Fix enum with trailing spaces
  core/src/test/scala/com/pingcap/tispark/datatype/BatchWriteDataTypeSuite.scala
Labels: needs-cherry-pick-2.4

#2128 Enable tests for read conflict
  core/src/test/scala/com/pingcap/tispark/concurrency/WriteReadSuite.scala
Labels: needs-cherry-pick-2.4

#2135 Fix not leader error due to region not invalidated
  tikv-client/src/main/java/com/pingcap/tikv/codec/KeyUtils.java
  tikv-client/src/main/java/com/pingcap/tikv/region/RegionManager.java
  tikv-client/src/main/java/com/pingcap/tikv/region/TiRegion.java
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4

#2126 Fix BatchGet StackOverFlow Error
  tikv-client/src/main/java/com/pingcap/tikv/KVClient.java
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4
