Repository pingcap/tispark, pull requests merged in 2021-04, with the labels that each got.

#1993 do not select tidb_row_format_version if tidb is 3.x
  core/src/main/scala/com/pingcap/tispark/write/TiBatchWrite.scala
  core/src/main/scala/com/pingcap/tispark/write/TiBatchWriteTable.scala
Labels: needs-cherry-pick-2.4, needs-cherry-pick-master

#1996 use comment to create clustered index table in test
  core/src/test/scala/org/apache/spark/sql/IssueTestSuite.scala
  core/src/test/scala/org/apache/spark/sql/clustered/ClusteredIndexTest.scala
  core/src/test/scala/org/apache/spark/sql/test/SharedSQLContext.scala
  core/src/test/scala/org/apache/spark/sql/test/generator/Schema.scala
Labels: needs-cherry-pick-2.4

#2002 Fix bigint handle overflow
  core/src/test/scala/org/apache/spark/sql/IssueTestSuite.scala
  tikv-client/src/main/java/com/pingcap/tikv/key/IntHandle.java
Labels: needs-cherry-pick-2.4

#2006 fix clustered index read + GregorianCalendar
  core/src/test/scala/org/apache/spark/sql/IssueTestSuite.scala
  tikv-client/src/main/java/com/pingcap/tikv/columnar/TiBlockColumnVector.java
  tikv-client/src/main/java/com/pingcap/tikv/columnar/TiChunkColumnVector.java
  tikv-client/src/main/java/com/pingcap/tikv/columnar/TiRowColumnVector.java
  tikv-client/src/main/java/com/pingcap/tikv/types/DateType.java
Labels: needs-cherry-pick-2.3

#2007 [cherry pick] fix clustered index read + GregorianCalendar (#2006)
  tikv-client/src/main/java/com/pingcap/tikv/columnar/TiBlockColumnVector.java
  tikv-client/src/main/java/com/pingcap/tikv/columnar/TiChunkColumnVector.java
  tikv-client/src/main/java/com/pingcap/tikv/columnar/TiRowColumnVector.java
  tikv-client/src/main/java/com/pingcap/tikv/types/DateType.java
Labels: CHERRY-PICK

#2004 update table statistics after batch write
  core/src/main/scala/com/pingcap/tispark/write/TiBatchWrite.scala
  core/src/main/scala/com/pingcap/tispark/write/TiBatchWriteTable.scala
  core/src/test/scala/com/pingcap/tispark/BatchWriteIssueSuite.scala
  tikv-client/src/main/java/com/pingcap/tikv/TiDBJDBCClient.java
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4

#2009 [cherry pick] update table statistics after batch write (#2004)
  core/src/main/scala/com/pingcap/tispark/write/TiBatchWrite.scala
  core/src/main/scala/com/pingcap/tispark/write/TiBatchWriteTable.scala
  core/src/test/scala/com/pingcap/tispark/BatchWriteIssueSuite.scala
  tikv-client/src/main/java/com/pingcap/tikv/TiDBJDBCClient.java
Labels: CHERRY-PICK

#2010 fix oom cause missing data bug
  tikv-client/src/main/java/com/pingcap/tikv/operation/iterator/DAGIterator.java
Labels: needs-cherry-pick-2.1, needs-cherry-pick-2.4, needs-cherry-pick-master

#2011 add argument: enableUpdateTableStatistics
  core/src/main/scala/com/pingcap/tispark/write/TiBatchWrite.scala
  core/src/main/scala/com/pingcap/tispark/write/TiDBOptions.scala
  core/src/test/scala/com/pingcap/tispark/BatchWriteIssueSuite.scala
  docs/datasource_api_userguide.md
Labels: needs-cherry-pick-2.4, needs-cherry-pick-master

#2017 release tispark 2.3.14
  CHANGELOG.md
  README.md
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4

#2021 release tispark 2.4.0
  CHANGELOG.md
  README.md
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4

#2025 add document: GRPC message exceeds maximum size error
  docs/userguide.md
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4

#2028 change PARTITION_PER_SPLIT default value from 1 to 10
  core/src/main/scala/com/pingcap/tispark/utils/TiUtil.scala
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4

#2031 ignore stats_meta update modify_count test
  core/src/test/scala/com/pingcap/tispark/BatchWriteIssueSuite.scala
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4

#2035 update log level to debug: invalid tiflash table replica sync progress
  tikv-client/src/main/java/com/pingcap/tikv/PDClient.java
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4

#2038 revert https://github.com/pingcap/tispark/pull/1969/
  .ci/tidb_config-for-tiflash-test.properties
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4

#1964 Fix array index out of bound when encoding
  tikv-client/src/main/java/com/pingcap/tikv/codec/RowEncoderV2.java
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4

#2000 shade gson
  tikv-client/pom.xml
Labels: needs-cherry-pick-2.4, needs-cherry-pick-master

#2046 fix batch write missing unpersist
  core/src/main/scala/com/pingcap/tispark/write/TiBatchWrite.scala
  core/src/main/scala/com/pingcap/tispark/write/TiBatchWriteTable.scala
Labels: needs-cherry-pick-2.4, needs-cherry-pick-master

#2054 fix bug: write decimal(16, 4) using batch write and read using tiflash
  tikv-client/src/main/java/com/pingcap/tikv/codec/RowEncoderV2.java
  tikv-client/src/test/java/com/pingcap/tikv/codec/TableCodecV2Test.java
Labels: needs-cherry-pick-2.4, needs-cherry-pick-master

#2057 fix random test with tiflash enabled
  core/src/test/scala/org/apache/spark/sql/types/BaseRandomDataTypeTest.scala
Labels: needs-cherry-pick-2.4, needs-cherry-pick-master

#2061 ignore test: Test sql with limit without order by
  core/src/test/scala/org/apache/spark/sql/IssueTestSuite.scala
Labels: needs-cherry-pick-2.3, needs-cherry-pick-2.4

#2064 ignore enum type test
  core/src/test/scala/org/apache/spark/sql/SparkDataTypeTestSuite.scala
Labels: needs-cherry-pick-2.4

#2066 Fix mistake setting current_ts to 0
  tikv-client/src/main/java/com/pingcap/tikv/txn/LockResolverClientV4.java
Labels: needs-cherry-pick-2.4
