Repository pingcap/tispark, pull requests merged in 2022-11, with the labels that each got.

#2576 Select tiflash with RR strategy
  tikv-client/src/main/java/com/pingcap/tikv/region/RegionManager.java
  tikv-client/src/test/java/com/pingcap/tikv/GrpcUtils.java
  tikv-client/src/test/java/com/pingcap/tikv/RegionManagerTest.java
Labels: needs-cherry-pick-release-2.4, needs-cherry-pick-release-2.5, status/LGT2, status/can-merge, needs-cherry-pick-release-3.0

#2578 fix statistics
  core/src/main/scala/com/pingcap/tispark/TiConfigConst.scala
  core/src/main/scala/com/pingcap/tispark/TiTableReference.scala
  core/src/main/scala/org/apache/spark/sql/TiContext.scala
  core/src/main/scala/org/apache/spark/sql/TiExtensions.scala
  core/src/main/scala/org/apache/spark/sql/catalyst/rule/TiAuthRuleFactory.scala
  core/src/main/scala/org/apache/spark/sql/catalyst/rule/TiAuthorizationRule.scala
  core/src/main/scala/org/apache/spark/sql/catalyst/rule/TiStatisticsRuleFactory.scala
  core/src/test/scala/org/apache/spark/SharedSparkContext.scala
  core/src/test/scala/org/apache/spark/sql/catalyst/plans/logical/LogicalPlanTestSuite.scala
  core/src/test/scala/org/apache/spark/sql/statistics/StatisticsManagerSuite.scala
  core/src/test/scala/org/apache/spark/sql/test/SharedSQLContext.scala
  docs/userguide_2.0.md
  docs/userguide_3.0.md
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-3.0, needs-cherry-pick-release-3.1

#2593 Support partition pruning with to_days function
  core/src/test/scala/org/apache/spark/sql/PartitionTableSuite.scala
  docs/userguide_3.0.md
  tikv-client/src/main/java/com/pingcap/tikv/expression/FuncCallExpr.java
  tikv-client/src/main/java/com/pingcap/tikv/expression/FuncCallExprEval.java
  tikv-client/src/main/java/com/pingcap/tikv/expression/RangePartitionPruner.java
  tikv-client/src/main/java/com/pingcap/tikv/expression/visitor/PartAndFilterExprRewriter.java
  tikv-client/src/main/java/com/pingcap/tikv/parser/AstBuilder.java
  tikv-client/src/main/java/com/pingcap/tikv/types/Converter.java
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-3.1

#2575 Optimize region not find
  tikv-client/src/main/java/com/pingcap/tikv/region/RegionManager.java
  tikv-client/src/main/java/com/pingcap/tikv/region/RegionStoreClient.java
Labels: needs-cherry-pick-release-2.4, needs-cherry-pick-release-2.5, status/LGT2, status/can-merge, needs-cherry-pick-release-3.0
