Repository pingcap/tispark, pull requests merged in 2022-08, with the labels that each got.

#2473 Fix: exception when the size of pdAddresse is > 1
  core/src/main/scala/com/pingcap/tispark/auth/TiAuthorization.scala
  core/src/main/scala/com/pingcap/tispark/telemetry/TiSparkTeleInfo.scala
  core/src/main/scala/org/apache/spark/sql/TiContext.scala
  core/src/main/scala/org/apache/spark/sql/catalyst/catalog/TiCatalog.scala
  core/src/test/scala/com/pingcap/tispark/auth/TiAuthIntegrationSuite.scala
  tikv-client/src/main/java/com/pingcap/tikv/jdbc/JDBCClient.java
Labels: needs-cherry-pick-release-2.5, status/LGT2, status/can-merge, needs-cherry-pick-release-3.0

#2476 fix count(bit) push down
  core/src/test/scala/org/apache/spark/sql/pushdown/CountPushDownSuite.scala
  tikv-client/src/main/java/com/pingcap/tikv/StoreVersion.java
Labels: needs-cherry-pick-release-2.4, needs-cherry-pick-release-2.5, status/LGT2, status/can-merge, needs-cherry-pick-release-3.0

#2482 Fix binary Range column partition test before v5.1.0
  core/src/test/scala/com/pingcap/tispark/partition/PartitionWriteSuite.scala
Labels: status/LGT2, status/can-merge

#2481 fix bug test fail in tidb4.0 test
  core/src/main/scala/com/pingcap/tispark/utils/TwoPhaseCommitHepler.scala
  core/src/main/scala/com/pingcap/tispark/write/TiBatchWrite.scala
  core/src/test/scala/com/pingcap/tispark/partition/PartitionWriteSuite.scala
  core/src/test/scala/org/apache/spark/sql/BaseTiSparkTest.scala
  core/src/test/scala/org/apache/spark/sql/catalyst/plans/logical/LogicalPlanTestSuite.scala
  core/src/test/scala/org/apache/spark/sql/insertion/BatchWritePKAndIndexSuite.scala
  core/src/test/scala/org/apache/spark/sql/pushdown/CountPushDownSuite.scala
  core/src/test/scala/org/apache/spark/sql/test/SharedSQLContext.scala
  tikv-client/src/main/java/com/pingcap/tikv/StoreVersion.java
  tikv-client/src/main/java/com/pingcap/tikv/region/RegionStoreClient.java
  tikv-client/src/test/java/com/pingcap/tikv/txn/LockResolverTest.java
Labels: status/LGT2, status/can-merge

#2486 upgrade spark
  pom.xml
Labels: needs-cherry-pick-release-2.5, status/LGT2, status/can-merge, needs-cherry-pick-release-3.0

#2464 [Design] Tispark support insert using SQL
  docs/design/2022-07-20-insert-support.md
Labels: status/LGT2, status/can-merge

#2489 Only do auth check for tables in TiDB
  core/src/main/scala/org/apache/spark/sql/catalyst/analyzer/TiAuthorizationRule.scala
  core/src/test/scala/com/pingcap/tispark/auth/TiAuthIntegrationSuite.scala
Labels: needs-cherry-pick-release-2.5, status/LGT2, status/can-merge, needs-cherry-pick-release-3.0

#2471 [Code] Tispark support insert using SQL
  core/src/main/java/com/pingcap/tikv/datatype/TypeMapping.java
  core/src/main/scala/com/pingcap/tispark/utils/ReflectionUtil.scala
  core/src/main/scala/com/pingcap/tispark/v2/TiDBTable.scala
  core/src/main/scala/com/pingcap/tispark/v2/sink/TiDBWriteBuilder.scala
  core/src/main/scala/com/pingcap/tispark/write/TiBatchWrite.scala
  core/src/main/scala/com/pingcap/tispark/write/TiBatchWriteTable.scala
  core/src/main/scala/com/pingcap/tispark/write/TiDBOptions.scala
  core/src/main/scala/com/pingcap/tispark/write/TiDBWriter.scala
  core/src/main/scala/org/apache/spark/sql/execution/TiConverter.scala
  core/src/test/scala/com/pingcap/tispark/concurrency/WriteDDLConflictSuite.scala
  core/src/test/scala/com/pingcap/tispark/concurrency/WriteWriteConflictSuite.scala
  core/src/test/scala/com/pingcap/tispark/convert/ToSignedSuite.scala
  core/src/test/scala/com/pingcap/tispark/datatype/BatchWriteDataTypeSuite.scala
  core/src/test/scala/com/pingcap/tispark/insert/InsertSuite.scala
  core/src/test/scala/com/pingcap/tispark/tablelock/TableLockSuite.scala
  core/src/test/scala/org/apache/spark/sql/types/BaseRandomDataTypeTest.scala
  db-random-test/src/main/scala/com/pingcap/tispark/test/generator/DataGenerator.scala
  docs/datasource_api_userguide.md
  docs/insert_sql_userguide.md
  spark-wrapper/spark-3.0/src/main/scala/org/apache/spark/sql/connector/write/TiDBWriteBuilder.scala
  spark-wrapper/spark-3.1/src/main/scala/org/apache/spark/sql/connector/write/TiDBWriteBuilder.scala
  spark-wrapper/spark-3.2/src/main/scala/org/apache/spark/sql/connector/write/TiDBWriteBuilder.scala
  tikv-client/src/main/java/com/pingcap/tikv/columnar/TiChunkColumnVector.java
  tikv-client/src/main/java/com/pingcap/tikv/types/BytesType.java
Labels: status/LGT2, status/can-merge

#2501 auth test fix
  core/src/test/scala/com/pingcap/tispark/auth/TiAuthIntegrationSuite.scala
Labels: status/LGT2, status/can-merge

#2500 only do auth check for TiDB (cherry-pick of #2489)
  core/src/main/scala/org/apache/spark/sql/catalyst/analyzer/TiAuthorizationRule.scala
  core/src/test/scala/com/pingcap/tispark/auth/TiAuthIntegrationSuite.scala
Labels: status/LGT2, status/can-merge

#2497 TiSpark Development Guide
  docs/dev/code_style.md
  docs/dev/commit_the_code_and_submit_a_pull_request.md
  docs/dev/get_the_code_build_and_run.md
  docs/dev/install_scala_java_spark_maven.md
  docs/dev/overview.md
  docs/dev/pics/conflict.png
  docs/dev/pics/fork.png
  docs/dev/pics/issue_choose.png
  docs/dev/pics/issue_template.png
  docs/dev/pics/java_format.png
  docs/dev/pics/overview.png
  docs/dev/pics/pr.png
  docs/dev/pics/pr_templete.png
  docs/dev/pics/scala_format.png
  docs/dev/report_an_issue.md
  docs/dev/start_tidb_cluster.md
  docs/dev/tispark_development_guide.md
  docs/dev/write.md
Labels: status/LGT2, status/can-merge

#2502 only do auth check for TiDB (cherry-pick of #2489)
  core/src/test/scala/com/pingcap/tispark/auth/TiAuthIntegrationSuite.scala
  spark-wrapper/spark-3.0/src/main/scala/org/apache/spark/sql/extensions/TiAuthorizationRule.scala
  spark-wrapper/spark-3.1/src/main/scala/org/apache/spark/sql/extensions/TiAuthorizationRule.scala
Labels: status/LGT2, status/can-merge

#2503 delete Python & R
  .github/workflows/codeql-analysis.yml
  R/README.md
  docs/userguide.md
  docs/userguide_spark2.1.md
  python/README.md
  python/README_spark2.1.md
  python/resources/spark-2.3/session.py
Labels: status/LGT2, status/can-merge

#2513 add Aggregates in TiDAGRequest (#2371)
  core/src/test/scala/com/pingcap/tispark/auth/TiAuthIntegrationSuite.scala
  core/src/test/scala/org/apache/spark/sql/pushdown/SumPushDownSuite.scala
Labels: status/LGT2, status/can-merge

#2517 change profile to 3.0 3.1
  pom.xml
Labels: status/LGT2, status/can-merge

#2518 changed the profile of 3.0
  pom.xml
Labels: status/LGT2, status/can-merge

#2512 add Aggregates in TiDAGRequest (#2371)
  core/src/test/scala/org/apache/spark/sql/pushdown/SumPushDownSuite.scala
  tikv-client/src/main/java/com/pingcap/tikv/meta/TiDAGRequest.java
Labels: status/LGT2, status/can-merge

#2515 fix: Incorrect unique index key when table is not intHandle & Duplicate values for unique indexes (#2455)
  core/src/main/scala/com/pingcap/tispark/utils/WriteUtil.scala
  core/src/main/scala/com/pingcap/tispark/write/TiBatchWriteTable.scala
  core/src/test/scala/org/apache/spark/sql/insertion/BatchWritePKAndIndexSuite.scala
  tikv-client/src/main/java/com/pingcap/tikv/codec/TableCodec.java
  tikv-client/src/main/java/com/pingcap/tikv/key/IndexKey.java
  tikv-client/src/main/java/com/pingcap/tikv/meta/TiTableInfo.java
  tikv-client/src/test/java/com/pingcap/tikv/codec/TableCodecTest.java
  tikv-client/src/test/java/com/pingcap/tikv/key/IndexKeyTest.java
  tikv-client/src/test/java/com/pingcap/tikv/meta/MetaUtils.java
Labels: status/LGT2, status/can-merge

#2516 fix: Incorrect unique index key when table is not intHandle & Duplicate values for unique indexes (#2455)
  core/src/main/scala/com/pingcap/tispark/write/TiBatchWriteTable.scala
  core/src/test/scala/org/apache/spark/sql/insertion/BatchWritePKAndIndexSuite.scala
  tikv-client/src/main/java/com/pingcap/tikv/codec/TableCodec.java
  tikv-client/src/main/java/com/pingcap/tikv/key/IndexKey.java
  tikv-client/src/main/java/com/pingcap/tikv/meta/TiTableInfo.java
  tikv-client/src/test/java/com/pingcap/tikv/codec/TableCodecTest.java
  tikv-client/src/test/java/com/pingcap/tikv/key/IndexKeyTest.java
  tikv-client/src/test/java/com/pingcap/tikv/meta/MetaUtils.java
Labels: status/LGT2, status/can-merge

#2528 Fix test failed in relase4.0
  core/src/test/scala/org/apache/spark/sql/catalyst/plans/logical/LogicalPlanTestSuite.scala
Labels: status/LGT2, status/can-merge
