Repository pingcap/tispark, pull requests merged in 2022-07, with the labels that each got.

#2433 fix region may be missed
  tikv-client/src/main/java/com/pingcap/tikv/operation/iterator/ConcreteScanIterator.java
Labels: status/LGT2, status/can-merge

#2386 [Design Doc] Make explanation of physical plan more clear
  docs/design/2022-06-15-phyical_plan_explain.md
  docs/design/imgs/phyical_plan_explain/code_flow_chart.png
Labels: status/LGT2, status/can-merge

#2446 fix license checker
  .github/workflows/license-check.yml
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-3.0

#2443 fix delete_userguide typo
  docs/delete_userguide.md
Labels: status/LGT2, status/can-merge

#2439 Make TiSpark's Explain clearer and easier to read
  .github/workflows/alter-primary-key-false-test.yml
  core/src/main/scala/org/apache/spark/sql/execution/CoprocessorRDD.scala
  core/src/test/scala/org/apache/spark/sql/InvisibleIndexSuite.scala
  core/src/test/scala/org/apache/spark/sql/catalyst/plans/BasePlanTest.scala
  core/src/test/scala/org/apache/spark/sql/catalyst/plans/logical/LogicalPlanTestSuite.scala
  core/src/test/scala/org/apache/spark/sql/catalyst/plans/statistics/StatisticsTestSuite.scala
  docker-compose-4.0.yaml
  docs/query_execution_plan_in_TiSpark.md
  tikv-client/src/main/java/com/pingcap/tikv/meta/TiDAGRequest.java
  tikv-client/src/main/java/com/pingcap/tikv/operation/SchemaInfer.java
  tikv-client/src/main/java/com/pingcap/tikv/operation/iterator/CoprocessorIterator.java
  tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java
  tikv-client/src/test/java/com/pingcap/tikv/meta/TiDAGRequestTest.java
  tikv-client/src/test/java/com/pingcap/tikv/operation/SchemaInferTest.java
  tikv-client/src/test/java/com/pingcap/tikv/operation/iterator/DAGIteratorTest.java
Labels: status/LGT2, status/can-merge

#2457 GPL fix
  README.md
  assembly/pom.xml
  assembly/src/main/assembly/assembly.xml
  core-test/pom.xml
  core/pom.xml
  core/src/test/scala/org/apache/spark/sql/QueryTest.scala
  pom.xml
Labels: needs-cherry-pick-release-2.4, needs-cherry-pick-release-2.5, status/LGT2, status/can-merge, needs-cherry-pick-release-3.0

#2438 [Design]Support bypass-TiDB write partition table with DataSource API
  docs/design/2022-06-30-partition-table-batchwrite-suppport.md
Labels: status/LGT2, status/can-merge

#2451 [Code]Support bypass-TiDB write partition table with DataSource API
  core/src/main/scala/com/pingcap/tispark/utils/TwoPhaseCommitHepler.scala
  core/src/main/scala/com/pingcap/tispark/utils/WriteUtil.scala
  core/src/main/scala/com/pingcap/tispark/v2/TiDBTable.scala
  core/src/main/scala/com/pingcap/tispark/write/TiBatchWrite.scala
  core/src/main/scala/com/pingcap/tispark/write/TiBatchWriteTable.scala
  core/src/main/scala/com/pingcap/tispark/write/TiDBDelete.scala
  core/src/main/scala/org/apache/spark/sql/catalyst/catalog/TiCatalog.scala
  core/src/test/scala/com/pingcap/tispark/datasource/CheckUnsupportedSuite.scala
  core/src/test/scala/com/pingcap/tispark/delete/DeleteNotSupportSuite.scala
  core/src/test/scala/com/pingcap/tispark/delete/DeleteWhereClauseSuite.scala
  core/src/test/scala/com/pingcap/tispark/partition/PartitionWriteSuite.scala
  docs/userguide.md
  tikv-client/pom.xml
  tikv-client/src/main/java/com/pingcap/tikv/TiBatchWriteUtils.java
  tikv-client/src/main/java/com/pingcap/tikv/expression/ColumnRef.java
  tikv-client/src/main/java/com/pingcap/tikv/expression/FuncCallExpr.java
  tikv-client/src/main/java/com/pingcap/tikv/expression/FuncCallExprEval.java
  tikv-client/src/main/java/com/pingcap/tikv/expression/PartitionPruner.java
  tikv-client/src/main/java/com/pingcap/tikv/expression/RangeColumnPartitionPruner.java
  tikv-client/src/main/java/com/pingcap/tikv/expression/visitor/RangePartitionLocator.java
  tikv-client/src/main/java/com/pingcap/tikv/meta/TiPartitionExpr.java
  tikv-client/src/main/java/com/pingcap/tikv/parser/AstBuilder.java
  tikv-client/src/main/java/com/pingcap/tikv/partition/PartitionExpression.java
  tikv-client/src/main/java/com/pingcap/tikv/partition/PartitionedTable.java
  tikv-client/src/main/java/com/pingcap/tikv/partition/TableCommon.java
  tikv-client/src/main/java/com/pingcap/tikv/types/BytesType.java
  tikv-client/src/main/java/com/pingcap/tikv/types/Converter.java
  tikv-client/src/test/java/com/pingcap/tikv/expression/visitor/PartitionLocatorTest.java
Labels: status/LGT2, status/can-merge

#2348 com.pingcap,tikv.key : bug fix reslove bug of cannot encode row key with non-long type ref: #2290
  core/src/test/scala/org/apache/spark/sql/catalyst/plans/logical/LogicalPlanTestSuite.scala
  tikv-client/src/main/java/com/pingcap/tikv/expression/Constant.java
  tikv-client/src/main/java/com/pingcap/tikv/meta/TiDAGRequest.java
  tikv-client/src/main/java/com/pingcap/tikv/predicates/IndexRange.java
  tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java
  tikv-client/src/test/java/com/pingcap/tikv/predicates/TiKVScanAnalyzerTest.java
Labels: status/LGT2, status/can-merge

#2436 Support host mapping in TiSpark
  core/pom.xml
  core/src/main/java/com/pingcap/tikv/hostmap/UriHostMapping.java
  core/src/main/scala/com/pingcap/tispark/TiConfigConst.scala
  core/src/main/scala/com/pingcap/tispark/telemetry/TiSparkTeleInfo.scala
  core/src/main/scala/com/pingcap/tispark/utils/TiUtil.scala
  core/src/main/scala/org/apache/spark/sql/catalyst/catalog/TiCatalog.scala
  core/src/test/scala/com/pingcap/tispark/hostmap/HostMappingSuite.scala
  docs/configuration.md
  tikv-client/src/main/java/com/pingcap/tikv/AbstractGRPCClient.java
  tikv-client/src/main/java/com/pingcap/tikv/DefaultHostMapping.java
  tikv-client/src/main/java/com/pingcap/tikv/PDClient.java
  tikv-client/src/main/java/com/pingcap/tikv/ReadOnlyPDClient.java
  tikv-client/src/main/java/com/pingcap/tikv/TiConfiguration.java
  tikv-client/src/main/java/com/pingcap/tikv/region/AbstractRegionStoreClient.java
  tikv-client/src/main/java/com/pingcap/tikv/region/RegionStoreClient.java
  tikv-client/src/main/java/com/pingcap/tikv/util/ChannelFactory.java
  tikv-client/src/main/java/com/pingcap/tikv/util/HostMapping.java
  tikv-client/src/test/java/com/pingcap/tikv/ChannelFactoryTest.java
Labels: status/LGT2, status/can-merge

#2455 fix: Incorrect unique index key when table is not intHandle & Duplicate values for unique indexes
  core/src/main/scala/com/pingcap/tispark/utils/WriteUtil.scala
  core/src/main/scala/com/pingcap/tispark/write/TiBatchWriteTable.scala
  core/src/test/scala/org/apache/spark/sql/insertion/BatchWritePKAndIndexSuite.scala
  tikv-client/src/main/java/com/pingcap/tikv/codec/TableCodec.java
  tikv-client/src/main/java/com/pingcap/tikv/key/IndexKey.java
  tikv-client/src/main/java/com/pingcap/tikv/meta/TiTableInfo.java
  tikv-client/src/test/java/com/pingcap/tikv/codec/TableCodecTest.java
  tikv-client/src/test/java/com/pingcap/tikv/key/IndexKeyTest.java
  tikv-client/src/test/java/com/pingcap/tikv/meta/MetaUtils.java
Labels: status/LGT2, status/can-merge
