Repository pingcap/tispark, pull requests merged in 2022-10, with the labels that each got.

#2560 support cluster index scan ref:#2453
  core/src/test/scala/org/apache/spark/sql/catalyst/plans/logical/LogicalPlanTestSuite.scala
  core/src/test/scala/org/apache/spark/sql/clustered/IndexScan0Suite.scala
  core/src/test/scala/org/apache/spark/sql/types/pk/ClusterIndexScanSuites.scala
  core/src/test/scala/org/apache/spark/sql/types/pk/MultiColumnClusterIndexDataSuite00.scala
  core/src/test/scala/org/apache/spark/sql/types/pk/MultiColumnPKDataTypeSuites.scala
  tikv-client/src/main/java/com/pingcap/tikv/key/CommonHandleScanKeyRangeBuilder.java
  tikv-client/src/main/java/com/pingcap/tikv/key/RowKey.java
  tikv-client/src/main/java/com/pingcap/tikv/meta/TiColumnInfo.java
  tikv-client/src/main/java/com/pingcap/tikv/meta/TiIndexInfo.java
  tikv-client/src/main/java/com/pingcap/tikv/meta/TiTableInfo.java
  tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java
  tikv-client/src/test/java/com/pingcap/tikv/predicates/TiKVScanAnalyzerTest.java
Labels: status/LGT2, status/can-merge

#2561 Release 2.4.4
  CHANGELOG.md
  assembly/pom.xml
  core-test/pom.xml
  core/pom.xml
  core/scripts/version.sh
  db-random-test/pom.xml
  pom.xml
  spark-wrapper/spark-2.3/pom.xml
  spark-wrapper/spark-2.4/pom.xml
  tikv-client/pom.xml
Labels: status/LGT2, status/can-merge

#2562 delete scala default value
  pom.xml
Labels: status/LGT2, status/can-merge

#2564 Alter artifactId for release-2.4
  assembly/pom.xml
  core-test/pom.xml
  core/pom.xml
  db-random-test/pom.xml
  pom.xml
  spark-wrapper/spark-2.3/pom.xml
  spark-wrapper/spark-2.4/pom.xml
  tikv-client/pom.xml
Labels: status/LGT2, status/can-merge

#2563 Enhancement CBO
  tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java
Labels: needs-cherry-pick-release-2.4, needs-cherry-pick-release-2.5, status/LGT2, status/can-merge, needs-cherry-pick-release-3.0, needs-cherry-pick-release-3.1

#2565 Partition write support new collations
  core/src/test/scala/com/pingcap/tispark/partition/PartitionBaseSuite.scala
  core/src/test/scala/com/pingcap/tispark/partition/PartitionNewCollationSuite.scala
  core/src/test/scala/com/pingcap/tispark/partition/PartitionWriteSuite.scala
  docs/userguide_3.0.md
  tikv-client/src/main/java/com/pingcap/tikv/expression/visitor/RangePartitionLocator.java
  tikv-client/src/test/java/com/pingcap/tikv/expression/visitor/PartitionLocatorTest.java
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-3.1
