Repository pingcap/tispark, pull requests merged in 2022-12, with the labels that each got.

#2599 Fix partition pruning with uppercase column
  core/src/test/scala/org/apache/spark/sql/PartitionTableSuite.scala
  tikv-client/src/main/java/com/pingcap/tikv/expression/ColumnRef.java
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-3.1

#2598 Compatible with TiDB mater (v6.5.0)
  core/src/test/scala/com/pingcap/tispark/datasource/AutoIncrementSuite.scala
  db-random-test/src/main/scala/com/pingcap/tispark/test/generator/IndexColumn.scala
  tikv-client/src/main/java/com/pingcap/tikv/handle/CommonHandle.java
  tikv-client/src/main/java/com/pingcap/tikv/types/DateType.java
Labels: needs-cherry-pick-release-2.4, needs-cherry-pick-release-2.5, status/LGT2, status/can-merge, needs-cherry-pick-release-3.0, needs-cherry-pick-release-3.1

#2606 Release 3.1.2
  CHANGELOG.md
  assembly/pom.xml
  core-test/pom.xml
  core/pom.xml
  core/src/test/scala/org/apache/spark/sql/test/SharedSQLContext.scala
  db-random-test/pom.xml
  pom.xml
  spark-wrapper/spark-3.0/pom.xml
  spark-wrapper/spark-3.1/pom.xml
  spark-wrapper/spark-3.2/pom.xml
  spark-wrapper/spark-3.3/pom.xml
  tikv-client/pom.xml
Labels: status/LGT2, status/can-merge

#2577 remove statement: TiSpark provides HTAP solution
  README.md
Labels: status/LGT2, status/can-merge

#2607 Add changelog for 3.1.2
  CHANGELOG.md
  pom.xml
Labels: status/LGT2, status/can-merge

#2608 Fix cache miss and delete an useless test
  core/src/test/scala/com/pingcap/tispark/BatchWriteIssueSuite.scala
  tikv-client/src/main/java/com/pingcap/tikv/util/RangeSplitter.java
Labels: status/LGT2, status/can-merge
