Repository pingcap/tispark, pull requests merged in 2023-03, with the labels that each got.

#2630 Update tls_reload_interval description in userguide_3.0.md
  docs/userguide_3.0.md
Labels: status/LGT2, status/can-merge

#2637 opimize partition table doc
  docs/userguide_3.0.md
Labels: status/LGT2, status/can-merge

#2643 Fix typo
  CHANGELOG.md
Labels: status/LGT2, status/can-merge

#2642 service_safe_point
  core/src/main/scala/com/pingcap/tispark/TiConfigConst.scala
  core/src/main/scala/com/pingcap/tispark/safepoint/ServiceSafePoint.scala
  core/src/main/scala/com/pingcap/tispark/write/TiBatchWrite.scala
  core/src/main/scala/org/apache/spark/sql/TiContext.scala
  spark-wrapper/spark-3.0/src/main/scala/org/apache/spark/sql/extensions/TiStrategy.scala
  spark-wrapper/spark-3.1/src/main/scala/org/apache/spark/sql/extensions/TiStrategy.scala
  spark-wrapper/spark-3.2/src/main/scala/org/apache/spark/sql/extensions/TiStrategy.scala
  spark-wrapper/spark-3.3/src/main/scala/org/apache/spark/sql/extensions/TiStrategy.scala
  tikv-client/pom.xml
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-3.2

#2631 Add gc doc
  README.md
  docs/features/datasource_api_userguide.md
  docs/features/partition_table.md
  docs/features/service_safe_point.md
  docs/userguide_3.0.md
Labels: status/LGT2, status/can-merge

#2641 Expose forward and set it to false in default
  core/src/main/scala/com/pingcap/tispark/TiConfigConst.scala
  core/src/main/scala/com/pingcap/tispark/utils/TiUtil.scala
  docs/userguide_3.0.md
  tikv-client/src/main/java/com/pingcap/tikv/TiConfiguration.java
  tikv-client/src/main/java/com/pingcap/tikv/util/ConvertUpstreamUtils.java
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-3.2

#2640 Probe tiflash
  docs/userguide_3.0.md
  tikv-client/scripts/proto.sh
  tikv-client/src/main/java/com/pingcap/tikv/ClientSession.java
  tikv-client/src/main/java/com/pingcap/tikv/TiConfiguration.java
  tikv-client/src/main/java/com/pingcap/tikv/TiFlashClient.java
  tikv-client/src/main/java/com/pingcap/tikv/operation/iterator/DAGIterator.java
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-3.2

#2639 Fix read from range column partition table error
  core/src/main/scala/org/apache/spark/sql/execution/CoprocessorRDD.scala
  core/src/test/scala/org/apache/spark/sql/PartitionTableSuite.scala
  docs/features/partition_table.md
  tikv-client/src/main/java/com/pingcap/tikv/expression/PartitionPruner.java
Labels: needs-cherry-pick-release-2.4, needs-cherry-pick-release-2.5, status/LGT2, status/can-merge, needs-cherry-pick-release-3.0, needs-cherry-pick-release-3.1, needs-cherry-pick-release-3.2

#2651 Support fallback when resolveLockAsync
  .github/workflows/license-check.yml
  .github/workflows/verify.yml
  core/src/main/scala/com/pingcap/tispark/safepoint/ServiceSafePoint.scala
  tikv-client/src/main/java/com/pingcap/tikv/exception/NonAsyncCommitLockException.java
  tikv-client/src/main/java/com/pingcap/tikv/region/RegionStoreClient.java
  tikv-client/src/main/java/com/pingcap/tikv/txn/AsyncResolveData.java
  tikv-client/src/main/java/com/pingcap/tikv/txn/LockResolverClientV4.java
  tikv-client/src/test/java/com/pingcap/tikv/txn/LockResolverAsyncCommitTest.java
  tikv-client/src/test/java/com/pingcap/tikv/txn/LockResolverTest.java
Labels: status/LGT2, status/can-merge

#2653 Fix the bug jvm not exit when enableAuth
  core/src/main/scala/com/pingcap/tispark/auth/TiAuthorization.scala
Labels: needs-cherry-pick-release-2.5, status/LGT2, status/can-merge, needs-cherry-pick-release-3.0, needs-cherry-pick-release-3.1, needs-cherry-pick-release-3.2

#2650 fix mutil_uniq
  core/src/test/scala/org/apache/spark/sql/IssueTestSuite.scala
  tikv-client/src/main/java/com/pingcap/tikv/meta/TiDAGRequest.java
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-3.1, needs-cherry-pick-release-3.2
