Repository pingcap/tispark, pull requests merged in 2023-04, with the labels that each got.

#2669 optimize ttl
  tikv-client/src/main/java/com/pingcap/tikv/allocator/RowIDAllocator.java
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-3.0, needs-cherry-pick-release-3.1, needs-cherry-pick-release-3.2

#2675 Update expired cert
  config/cert/jks/client-keystore
  config/cert/jks/server-cert-store
  config/cert/pem/client.pem
  config/cert/pem/root.srl
Labels: status/LGT2, status/can-merge

#2667 Do not reload table schema when update catalog cache
  .github/workflows/codeql-analysis.yml
  core/src/main/scala/com/pingcap/tispark/TiConfigConst.scala
  core/src/main/scala/com/pingcap/tispark/utils/TiUtil.scala
  docs/userguide_3.0.md
  tikv-client/src/main/java/com/pingcap/tikv/ClientSession.java
  tikv-client/src/main/java/com/pingcap/tikv/TiConfiguration.java
  tikv-client/src/main/java/com/pingcap/tikv/catalog/Catalog.java
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-3.0, needs-cherry-pick-release-3.1, needs-cherry-pick-release-3.2

#2686 update version to 3.0.3
  assembly/pom.xml
  core-test/pom.xml
  core/pom.xml
  db-random-test/pom.xml
  pom.xml
  spark-wrapper/spark-3.0/pom.xml
  spark-wrapper/spark-3.1/pom.xml
  spark-wrapper/spark-3.2/pom.xml
  tikv-client/pom.xml
Labels: status/LGT2, status/can-merge

#2690 Disable jackson FAIL_ON_UNKNOWN_PROPERTIES
  tikv-client/src/main/java/com/pingcap/tikv/catalog/CatalogTransaction.java
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-3.0, needs-cherry-pick-release-3.1, needs-cherry-pick-release-3.2

#2695 update client-java version to 3.3.4
  tikv-client/pom.xml
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-3.2

#2697 update version to 3.2.1
  assembly/pom.xml
  core-test/pom.xml
  core/pom.xml
  db-random-test/pom.xml
  spark-wrapper/spark-3.0/pom.xml
  spark-wrapper/spark-3.1/pom.xml
  spark-wrapper/spark-3.2/pom.xml
  spark-wrapper/spark-3.3/pom.xml
  tikv-client/pom.xml
Labels: status/LGT2, status/can-merge
