Repository pingcap/tispark, pull requests merged in 2023-05, with the labels that each got.

#2698 Set daemon thread to fix jvm not exit
  core/src/main/scala/com/pingcap/tispark/safepoint/ServiceSafePoint.scala
  tikv-client/src/main/java/com/pingcap/tikv/ClientSession.java
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-3.0, needs-cherry-pick-release-3.1, needs-cherry-pick-release-3.2

#2668 chore: migrate to new prow reviewing
  OWNERS
Labels: status/LGT2, status/can-merge

#2703 Add health check timeout
  core/src/main/scala/com/pingcap/tispark/TiConfigConst.scala
  core/src/main/scala/com/pingcap/tispark/utils/TiUtil.scala
  docs/userguide_3.0.md
  tikv-client/src/main/java/com/pingcap/tikv/ClientSession.java
  tikv-client/src/main/java/com/pingcap/tikv/TiConfiguration.java
  tikv-client/src/main/java/com/pingcap/tikv/TiFlashClient.java
  tikv-client/src/main/java/com/pingcap/tikv/operation/iterator/DAGIterator.java
  tikv-client/src/main/java/com/pingcap/tikv/util/ConvertUpstreamUtils.java
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-3.2
