Repository pingcap/tispark, pull requests merged in 2023-02, with the labels that each got.

#2621 Set default value of spark.tispark.telemetry.enable as false
  core/src/main/scala/org/apache/spark/sql/TiExtensions.scala
  docs/features/telemetry.md
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-3.0, needs-cherry-pick-release-3.1, needs-cherry-pick-release-3.2

#2626 Fix cacheInvalidateCallback does not work
  core/src/test/scala/com/pingcap/tispark/accumulator/AccumulatorSuite.scala
  core/src/test/scala/org/apache/spark/sql/catalyst/plans/logical/LogicalPlanTestSuite.scala
  tikv-client/src/main/java/com/pingcap/tikv/TiSession.java
  tikv-client/src/main/java/com/pingcap/tikv/region/RegionManager.java
Labels: needs-cherry-pick-release-2.4, needs-cherry-pick-release-2.5, status/LGT2, status/can-merge

#2629 fix dead link
  docs/userguide_3.0.md
Labels: status/LGT2, status/can-merge

#2619 Support probe tiflash status
  docs/userguide_3.0.md
  tikv-client/scripts/proto.sh
  tikv-client/src/main/java/com/pingcap/tikv/TiConfiguration.java
  tikv-client/src/main/java/com/pingcap/tikv/TiSession.java
  tikv-client/src/main/java/com/pingcap/tikv/operation/iterator/DAGIterator.java
  tikv-client/src/main/java/com/pingcap/tikv/region/AbstractRegionStoreClient.java
  tikv-client/src/main/java/com/pingcap/tikv/region/RegionManager.java
  tikv-client/src/main/java/com/pingcap/tikv/region/RegionStoreClient.java
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-3.0
